/* SQL text to insert 1 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[EntityField] WHERE ID = 'ca092b55-b63a-4288-bb13-ac74e31175af' OR (EntityID = '04E37D72-B573-4B81-B1E1-A501F1372851' AND Name = 'SaleConveyance')) BEGIN
         INSERT INTO [${flyway:defaultSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'ca092b55-b63a-4288-bb13-ac74e31175af',
            '04E37D72-B573-4B81-B1E1-A501F1372851', -- Entity: Sale Conveyance Members
            100025,
            'SaleConveyance',
            'Sale Conveyance',
            NULL,
            'nvarchar',
            400,
            0,
            0,
            0,
            NULL,
            0,
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to insert entity field value with ID a310ea82-b841-4736-b3e6-51685091e6dd */
INSERT INTO [${flyway:defaultSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('a310ea82-b841-4736-b3e6-51685091e6dd', '87FF5BF2-7A33-49DD-A2F9-ECC759C1C9F5', 3, 'S11', 'S11', GETUTCDATE(), GETUTCDATE());

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=4 WHERE ID='274695FA-4E85-492B-9DCF-6C782E956858';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=5 WHERE ID='8CF364C0-16F5-4696-B327-918DA6B3D125';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=6 WHERE ID='189424BF-549E-425A-A5AE-540BF6543A6A';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=7 WHERE ID='47E22781-0483-40B2-827C-BF7770E56288';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=8 WHERE ID='F6E41AAE-32F7-492D-8CAB-30BEE1A271C5';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=9 WHERE ID='06CAA1B5-AB00-459E-96DC-3AC89BD41E4C';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=10 WHERE ID='F04F016B-8929-4ACA-8BD5-4E5CB676EF66';

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=11 WHERE ID='709072C0-8EE5-4640-9734-9BA0C43BB015';

/* SQL text to update virtual entity field UnverifiedCompCount for entity Store Analysis */
UPDATE
                                    [${flyway:defaultSchema}].[EntityField]
                                  SET
                                    Sequence=70,
                                    Type='int',
                                    AllowsNull=1,
                                    
                                    Length=4,
                                    Precision=10,
                                    Scale=0
                                  WHERE
                                    ID = '377D324C-20CB-4A76-AB06-CB439830F01E';

/* Index for Foreign Keys for AppealRecommendationSignal */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendation Signals
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key AppealRecommendationID in table AppealRecommendationSignal
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AppealRecommendationSignal_AppealRecommendationID' 
    AND object_id = OBJECT_ID('[indiana_tax].[AppealRecommendationSignal]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AppealRecommendationSignal_AppealRecommendationID ON [indiana_tax].[AppealRecommendationSignal] ([AppealRecommendationID]);

/* Index for Foreign Keys for AppealRecommendation */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendations
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ParcelID in table AppealRecommendation
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AppealRecommendation_ParcelID' 
    AND object_id = OBJECT_ID('[indiana_tax].[AppealRecommendation]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AppealRecommendation_ParcelID ON [indiana_tax].[AppealRecommendation] ([ParcelID]);

-- Index for foreign key PropertyID in table AppealRecommendation
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AppealRecommendation_PropertyID' 
    AND object_id = OBJECT_ID('[indiana_tax].[AppealRecommendation]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AppealRecommendation_PropertyID ON [indiana_tax].[AppealRecommendation] ([PropertyID]);

/* Base View SQL for Appeal Recommendation Signals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendation Signals
-- Item: vwAppealRecommendationSignals
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Appeal Recommendation Signals
-----               SCHEMA:      indiana_tax
-----               BASE TABLE:  AppealRecommendationSignal
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[vwAppealRecommendationSignals]', 'V') IS NOT NULL
    DROP VIEW [indiana_tax].[vwAppealRecommendationSignals];
GO

CREATE VIEW [indiana_tax].[vwAppealRecommendationSignals]
AS
SELECT
    a.*
FROM
    [indiana_tax].[AppealRecommendationSignal] AS a
GO
GRANT SELECT ON [indiana_tax].[vwAppealRecommendationSignals] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for Appeal Recommendation Signals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendation Signals
-- Item: Permissions for vwAppealRecommendationSignals
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [indiana_tax].[vwAppealRecommendationSignals] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for Appeal Recommendation Signals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendation Signals
-- Item: spCreateAppealRecommendationSignal
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR AppealRecommendationSignal
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spCreateAppealRecommendationSignal]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spCreateAppealRecommendationSignal];
GO

CREATE PROCEDURE [indiana_tax].[spCreateAppealRecommendationSignal]
    @ID uniqueidentifier = NULL,
    @AppealRecommendationID uniqueidentifier,
    @SignalCode nvarchar(4),
    @Supports nvarchar(10),
    @NAReason_Clear bit = 0,
    @NAReason nvarchar(60) = NULL,
    @IndicatedValue_Clear bit = 0,
    @IndicatedValue decimal(18, 2) = NULL,
    @IndicatedPerUnit_Clear bit = 0,
    @IndicatedPerUnit decimal(14, 2) = NULL,
    @UnitOfComparison_Clear bit = 0,
    @UnitOfComparison nvarchar(10) = NULL,
    @EvidenceCount_Clear bit = 0,
    @EvidenceCount int = NULL,
    @EvidenceNote_Clear bit = 0,
    @EvidenceNote nvarchar(400) = NULL,
    @RuleVersion nvarchar(40)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [indiana_tax].[AppealRecommendationSignal]
            (
                [ID],
                [AppealRecommendationID],
                [SignalCode],
                [Supports],
                [NAReason],
                [IndicatedValue],
                [IndicatedPerUnit],
                [UnitOfComparison],
                [EvidenceCount],
                [EvidenceNote],
                [RuleVersion]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @AppealRecommendationID,
                @SignalCode,
                @Supports,
                CASE WHEN @NAReason_Clear = 1 THEN NULL ELSE ISNULL(@NAReason, NULL) END,
                CASE WHEN @IndicatedValue_Clear = 1 THEN NULL ELSE ISNULL(@IndicatedValue, NULL) END,
                CASE WHEN @IndicatedPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@IndicatedPerUnit, NULL) END,
                CASE WHEN @UnitOfComparison_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfComparison, NULL) END,
                CASE WHEN @EvidenceCount_Clear = 1 THEN NULL ELSE ISNULL(@EvidenceCount, NULL) END,
                CASE WHEN @EvidenceNote_Clear = 1 THEN NULL ELSE ISNULL(@EvidenceNote, NULL) END,
                @RuleVersion
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [indiana_tax].[AppealRecommendationSignal]
            (
                [AppealRecommendationID],
                [SignalCode],
                [Supports],
                [NAReason],
                [IndicatedValue],
                [IndicatedPerUnit],
                [UnitOfComparison],
                [EvidenceCount],
                [EvidenceNote],
                [RuleVersion]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @AppealRecommendationID,
                @SignalCode,
                @Supports,
                CASE WHEN @NAReason_Clear = 1 THEN NULL ELSE ISNULL(@NAReason, NULL) END,
                CASE WHEN @IndicatedValue_Clear = 1 THEN NULL ELSE ISNULL(@IndicatedValue, NULL) END,
                CASE WHEN @IndicatedPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@IndicatedPerUnit, NULL) END,
                CASE WHEN @UnitOfComparison_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfComparison, NULL) END,
                CASE WHEN @EvidenceCount_Clear = 1 THEN NULL ELSE ISNULL(@EvidenceCount, NULL) END,
                CASE WHEN @EvidenceNote_Clear = 1 THEN NULL ELSE ISNULL(@EvidenceNote, NULL) END,
                @RuleVersion
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [indiana_tax].[vwAppealRecommendationSignals] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [indiana_tax].[spCreateAppealRecommendationSignal] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for Appeal Recommendation Signals */

GRANT EXECUTE ON [indiana_tax].[spCreateAppealRecommendationSignal] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for Appeal Recommendation Signals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendation Signals
-- Item: spUpdateAppealRecommendationSignal
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR AppealRecommendationSignal
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spUpdateAppealRecommendationSignal]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spUpdateAppealRecommendationSignal];
GO

CREATE PROCEDURE [indiana_tax].[spUpdateAppealRecommendationSignal]
    @ID uniqueidentifier,
    @AppealRecommendationID uniqueidentifier = NULL,
    @SignalCode nvarchar(4) = NULL,
    @Supports nvarchar(10) = NULL,
    @NAReason_Clear bit = 0,
    @NAReason nvarchar(60) = NULL,
    @IndicatedValue_Clear bit = 0,
    @IndicatedValue decimal(18, 2) = NULL,
    @IndicatedPerUnit_Clear bit = 0,
    @IndicatedPerUnit decimal(14, 2) = NULL,
    @UnitOfComparison_Clear bit = 0,
    @UnitOfComparison nvarchar(10) = NULL,
    @EvidenceCount_Clear bit = 0,
    @EvidenceCount int = NULL,
    @EvidenceNote_Clear bit = 0,
    @EvidenceNote nvarchar(400) = NULL,
    @RuleVersion nvarchar(40) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[AppealRecommendationSignal]
    SET
        [AppealRecommendationID] = ISNULL(@AppealRecommendationID, [AppealRecommendationID]),
        [SignalCode] = ISNULL(@SignalCode, [SignalCode]),
        [Supports] = ISNULL(@Supports, [Supports]),
        [NAReason] = CASE WHEN @NAReason_Clear = 1 THEN NULL ELSE ISNULL(@NAReason, [NAReason]) END,
        [IndicatedValue] = CASE WHEN @IndicatedValue_Clear = 1 THEN NULL ELSE ISNULL(@IndicatedValue, [IndicatedValue]) END,
        [IndicatedPerUnit] = CASE WHEN @IndicatedPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@IndicatedPerUnit, [IndicatedPerUnit]) END,
        [UnitOfComparison] = CASE WHEN @UnitOfComparison_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfComparison, [UnitOfComparison]) END,
        [EvidenceCount] = CASE WHEN @EvidenceCount_Clear = 1 THEN NULL ELSE ISNULL(@EvidenceCount, [EvidenceCount]) END,
        [EvidenceNote] = CASE WHEN @EvidenceNote_Clear = 1 THEN NULL ELSE ISNULL(@EvidenceNote, [EvidenceNote]) END,
        [RuleVersion] = ISNULL(@RuleVersion, [RuleVersion])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [indiana_tax].[vwAppealRecommendationSignals] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [indiana_tax].[vwAppealRecommendationSignals]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [indiana_tax].[spUpdateAppealRecommendationSignal] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the AppealRecommendationSignal table
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[trgUpdateAppealRecommendationSignal]', 'TR') IS NOT NULL
    DROP TRIGGER [indiana_tax].[trgUpdateAppealRecommendationSignal];
GO
CREATE TRIGGER [indiana_tax].trgUpdateAppealRecommendationSignal
ON [indiana_tax].[AppealRecommendationSignal]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[AppealRecommendationSignal]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [indiana_tax].[AppealRecommendationSignal] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for Appeal Recommendation Signals */

GRANT EXECUTE ON [indiana_tax].[spUpdateAppealRecommendationSignal] TO [cdp_Developer], [cdp_Integration];

/* Base View SQL for Appeal Recommendations */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendations
-- Item: vwAppealRecommendations
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Appeal Recommendations
-----               SCHEMA:      indiana_tax
-----               BASE TABLE:  AppealRecommendation
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[vwAppealRecommendations]', 'V') IS NOT NULL
    DROP VIEW [indiana_tax].[vwAppealRecommendations];
GO

CREATE VIEW [indiana_tax].[vwAppealRecommendations]
AS
SELECT
    a.*,
    indianataxParcel_ParcelID.[ParcelNumber] AS [Parcel],
    indianataxProperty_PropertyID.[Name] AS [Property]
FROM
    [indiana_tax].[AppealRecommendation] AS a
LEFT OUTER JOIN
    [indiana_tax].[Parcel] AS indianataxParcel_ParcelID
  ON
    [a].[ParcelID] = indianataxParcel_ParcelID.[ID]
LEFT OUTER JOIN
    [indiana_tax].[Property] AS indianataxProperty_PropertyID
  ON
    [a].[PropertyID] = indianataxProperty_PropertyID.[ID]
GO
GRANT SELECT ON [indiana_tax].[vwAppealRecommendations] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for Appeal Recommendations */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendations
-- Item: Permissions for vwAppealRecommendations
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [indiana_tax].[vwAppealRecommendations] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for Appeal Recommendations */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendations
-- Item: spCreateAppealRecommendation
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR AppealRecommendation
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spCreateAppealRecommendation]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spCreateAppealRecommendation];
GO

CREATE PROCEDURE [indiana_tax].[spCreateAppealRecommendation]
    @ID uniqueidentifier = NULL,
    @SubjectKind nvarchar(10),
    @ParcelID_Clear bit = 0,
    @ParcelID uniqueidentifier = NULL,
    @PropertyID_Clear bit = 0,
    @PropertyID uniqueidentifier = NULL,
    @AssessmentYear int,
    @MethodologyVersion nvarchar(40),
    @IsCurrent bit = NULL,
    @CurrentAV_Clear bit = 0,
    @CurrentAV decimal(18, 2) = NULL,
    @PriorAVAsDetermined_Clear bit = 0,
    @PriorAVAsDetermined decimal(18, 2) = NULL,
    @UnitOfComparison_Clear bit = 0,
    @UnitOfComparison nvarchar(10) = NULL,
    @Denominator_Clear bit = 0,
    @Denominator decimal(14, 2) = NULL,
    @DenominatorSource_Clear bit = 0,
    @DenominatorSource nvarchar(20) = NULL,
    @DenominatorIsFallback bit = NULL,
    @ValueSignalCount tinyint,
    @IncreaseFlag bit,
    @FloorSupport bit,
    @PeerOutOfLine bit,
    @OwnSaleContrary bit,
    @Verdict nvarchar(16),
    @NotAvailableReason_Clear bit = 0,
    @NotAvailableReason nvarchar(60) = NULL,
    @ConfidenceTier_Clear bit = 0,
    @ConfidenceTier nvarchar(8) = NULL,
    @FloorValue_Clear bit = 0,
    @FloorValue decimal(18, 2) = NULL,
    @AskValue_Clear bit = 0,
    @AskValue decimal(18, 2) = NULL,
    @AskPolicy nvarchar(16),
    @AskBasis_Clear bit = 0,
    @AskBasis nvarchar(20) = NULL,
    @EstSavingsAtAsk_Clear bit = 0,
    @EstSavingsAtAsk decimal(14, 2) = NULL,
    @EstSavingsAtFloor_Clear bit = 0,
    @EstSavingsAtFloor decimal(14, 2) = NULL,
    @EffectiveTaxRate_Clear bit = 0,
    @EffectiveTaxRate decimal(9, 6) = NULL,
    @GroupingStatus nvarchar(20),
    @GroupingVersion_Clear bit = 0,
    @GroupingVersion datetime2 = NULL,
    @AlreadyAppealed bit,
    @ExistingRep_Clear bit = 0,
    @ExistingRep nvarchar(200) = NULL,
    @Exempt bit,
    @BelowSavingsFloor bit,
    @RunStamp datetime2,
    @GeneratedAt datetime2
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [indiana_tax].[AppealRecommendation]
            (
                [ID],
                [SubjectKind],
                [ParcelID],
                [PropertyID],
                [AssessmentYear],
                [MethodologyVersion],
                [IsCurrent],
                [CurrentAV],
                [PriorAVAsDetermined],
                [UnitOfComparison],
                [Denominator],
                [DenominatorSource],
                [DenominatorIsFallback],
                [ValueSignalCount],
                [IncreaseFlag],
                [FloorSupport],
                [PeerOutOfLine],
                [OwnSaleContrary],
                [Verdict],
                [NotAvailableReason],
                [ConfidenceTier],
                [FloorValue],
                [AskValue],
                [AskPolicy],
                [AskBasis],
                [EstSavingsAtAsk],
                [EstSavingsAtFloor],
                [EffectiveTaxRate],
                [GroupingStatus],
                [GroupingVersion],
                [AlreadyAppealed],
                [ExistingRep],
                [Exempt],
                [BelowSavingsFloor],
                [RunStamp],
                [GeneratedAt]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SubjectKind,
                CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, NULL) END,
                CASE WHEN @PropertyID_Clear = 1 THEN NULL ELSE ISNULL(@PropertyID, NULL) END,
                @AssessmentYear,
                @MethodologyVersion,
                ISNULL(@IsCurrent, 1),
                CASE WHEN @CurrentAV_Clear = 1 THEN NULL ELSE ISNULL(@CurrentAV, NULL) END,
                CASE WHEN @PriorAVAsDetermined_Clear = 1 THEN NULL ELSE ISNULL(@PriorAVAsDetermined, NULL) END,
                CASE WHEN @UnitOfComparison_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfComparison, NULL) END,
                CASE WHEN @Denominator_Clear = 1 THEN NULL ELSE ISNULL(@Denominator, NULL) END,
                CASE WHEN @DenominatorSource_Clear = 1 THEN NULL ELSE ISNULL(@DenominatorSource, NULL) END,
                ISNULL(@DenominatorIsFallback, 0),
                @ValueSignalCount,
                @IncreaseFlag,
                @FloorSupport,
                @PeerOutOfLine,
                @OwnSaleContrary,
                @Verdict,
                CASE WHEN @NotAvailableReason_Clear = 1 THEN NULL ELSE ISNULL(@NotAvailableReason, NULL) END,
                CASE WHEN @ConfidenceTier_Clear = 1 THEN NULL ELSE ISNULL(@ConfidenceTier, NULL) END,
                CASE WHEN @FloorValue_Clear = 1 THEN NULL ELSE ISNULL(@FloorValue, NULL) END,
                CASE WHEN @AskValue_Clear = 1 THEN NULL ELSE ISNULL(@AskValue, NULL) END,
                @AskPolicy,
                CASE WHEN @AskBasis_Clear = 1 THEN NULL ELSE ISNULL(@AskBasis, NULL) END,
                CASE WHEN @EstSavingsAtAsk_Clear = 1 THEN NULL ELSE ISNULL(@EstSavingsAtAsk, NULL) END,
                CASE WHEN @EstSavingsAtFloor_Clear = 1 THEN NULL ELSE ISNULL(@EstSavingsAtFloor, NULL) END,
                CASE WHEN @EffectiveTaxRate_Clear = 1 THEN NULL ELSE ISNULL(@EffectiveTaxRate, NULL) END,
                @GroupingStatus,
                CASE WHEN @GroupingVersion_Clear = 1 THEN NULL ELSE ISNULL(@GroupingVersion, NULL) END,
                @AlreadyAppealed,
                CASE WHEN @ExistingRep_Clear = 1 THEN NULL ELSE ISNULL(@ExistingRep, NULL) END,
                @Exempt,
                @BelowSavingsFloor,
                @RunStamp,
                @GeneratedAt
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [indiana_tax].[AppealRecommendation]
            (
                [SubjectKind],
                [ParcelID],
                [PropertyID],
                [AssessmentYear],
                [MethodologyVersion],
                [IsCurrent],
                [CurrentAV],
                [PriorAVAsDetermined],
                [UnitOfComparison],
                [Denominator],
                [DenominatorSource],
                [DenominatorIsFallback],
                [ValueSignalCount],
                [IncreaseFlag],
                [FloorSupport],
                [PeerOutOfLine],
                [OwnSaleContrary],
                [Verdict],
                [NotAvailableReason],
                [ConfidenceTier],
                [FloorValue],
                [AskValue],
                [AskPolicy],
                [AskBasis],
                [EstSavingsAtAsk],
                [EstSavingsAtFloor],
                [EffectiveTaxRate],
                [GroupingStatus],
                [GroupingVersion],
                [AlreadyAppealed],
                [ExistingRep],
                [Exempt],
                [BelowSavingsFloor],
                [RunStamp],
                [GeneratedAt]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SubjectKind,
                CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, NULL) END,
                CASE WHEN @PropertyID_Clear = 1 THEN NULL ELSE ISNULL(@PropertyID, NULL) END,
                @AssessmentYear,
                @MethodologyVersion,
                ISNULL(@IsCurrent, 1),
                CASE WHEN @CurrentAV_Clear = 1 THEN NULL ELSE ISNULL(@CurrentAV, NULL) END,
                CASE WHEN @PriorAVAsDetermined_Clear = 1 THEN NULL ELSE ISNULL(@PriorAVAsDetermined, NULL) END,
                CASE WHEN @UnitOfComparison_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfComparison, NULL) END,
                CASE WHEN @Denominator_Clear = 1 THEN NULL ELSE ISNULL(@Denominator, NULL) END,
                CASE WHEN @DenominatorSource_Clear = 1 THEN NULL ELSE ISNULL(@DenominatorSource, NULL) END,
                ISNULL(@DenominatorIsFallback, 0),
                @ValueSignalCount,
                @IncreaseFlag,
                @FloorSupport,
                @PeerOutOfLine,
                @OwnSaleContrary,
                @Verdict,
                CASE WHEN @NotAvailableReason_Clear = 1 THEN NULL ELSE ISNULL(@NotAvailableReason, NULL) END,
                CASE WHEN @ConfidenceTier_Clear = 1 THEN NULL ELSE ISNULL(@ConfidenceTier, NULL) END,
                CASE WHEN @FloorValue_Clear = 1 THEN NULL ELSE ISNULL(@FloorValue, NULL) END,
                CASE WHEN @AskValue_Clear = 1 THEN NULL ELSE ISNULL(@AskValue, NULL) END,
                @AskPolicy,
                CASE WHEN @AskBasis_Clear = 1 THEN NULL ELSE ISNULL(@AskBasis, NULL) END,
                CASE WHEN @EstSavingsAtAsk_Clear = 1 THEN NULL ELSE ISNULL(@EstSavingsAtAsk, NULL) END,
                CASE WHEN @EstSavingsAtFloor_Clear = 1 THEN NULL ELSE ISNULL(@EstSavingsAtFloor, NULL) END,
                CASE WHEN @EffectiveTaxRate_Clear = 1 THEN NULL ELSE ISNULL(@EffectiveTaxRate, NULL) END,
                @GroupingStatus,
                CASE WHEN @GroupingVersion_Clear = 1 THEN NULL ELSE ISNULL(@GroupingVersion, NULL) END,
                @AlreadyAppealed,
                CASE WHEN @ExistingRep_Clear = 1 THEN NULL ELSE ISNULL(@ExistingRep, NULL) END,
                @Exempt,
                @BelowSavingsFloor,
                @RunStamp,
                @GeneratedAt
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [indiana_tax].[vwAppealRecommendations] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [indiana_tax].[spCreateAppealRecommendation] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for Appeal Recommendations */

GRANT EXECUTE ON [indiana_tax].[spCreateAppealRecommendation] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for Appeal Recommendations */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendations
-- Item: spUpdateAppealRecommendation
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR AppealRecommendation
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spUpdateAppealRecommendation]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spUpdateAppealRecommendation];
GO

CREATE PROCEDURE [indiana_tax].[spUpdateAppealRecommendation]
    @ID uniqueidentifier,
    @SubjectKind nvarchar(10) = NULL,
    @ParcelID_Clear bit = 0,
    @ParcelID uniqueidentifier = NULL,
    @PropertyID_Clear bit = 0,
    @PropertyID uniqueidentifier = NULL,
    @AssessmentYear int = NULL,
    @MethodologyVersion nvarchar(40) = NULL,
    @IsCurrent bit = NULL,
    @CurrentAV_Clear bit = 0,
    @CurrentAV decimal(18, 2) = NULL,
    @PriorAVAsDetermined_Clear bit = 0,
    @PriorAVAsDetermined decimal(18, 2) = NULL,
    @UnitOfComparison_Clear bit = 0,
    @UnitOfComparison nvarchar(10) = NULL,
    @Denominator_Clear bit = 0,
    @Denominator decimal(14, 2) = NULL,
    @DenominatorSource_Clear bit = 0,
    @DenominatorSource nvarchar(20) = NULL,
    @DenominatorIsFallback bit = NULL,
    @ValueSignalCount tinyint = NULL,
    @IncreaseFlag bit = NULL,
    @FloorSupport bit = NULL,
    @PeerOutOfLine bit = NULL,
    @OwnSaleContrary bit = NULL,
    @Verdict nvarchar(16) = NULL,
    @NotAvailableReason_Clear bit = 0,
    @NotAvailableReason nvarchar(60) = NULL,
    @ConfidenceTier_Clear bit = 0,
    @ConfidenceTier nvarchar(8) = NULL,
    @FloorValue_Clear bit = 0,
    @FloorValue decimal(18, 2) = NULL,
    @AskValue_Clear bit = 0,
    @AskValue decimal(18, 2) = NULL,
    @AskPolicy nvarchar(16) = NULL,
    @AskBasis_Clear bit = 0,
    @AskBasis nvarchar(20) = NULL,
    @EstSavingsAtAsk_Clear bit = 0,
    @EstSavingsAtAsk decimal(14, 2) = NULL,
    @EstSavingsAtFloor_Clear bit = 0,
    @EstSavingsAtFloor decimal(14, 2) = NULL,
    @EffectiveTaxRate_Clear bit = 0,
    @EffectiveTaxRate decimal(9, 6) = NULL,
    @GroupingStatus nvarchar(20) = NULL,
    @GroupingVersion_Clear bit = 0,
    @GroupingVersion datetime2 = NULL,
    @AlreadyAppealed bit = NULL,
    @ExistingRep_Clear bit = 0,
    @ExistingRep nvarchar(200) = NULL,
    @Exempt bit = NULL,
    @BelowSavingsFloor bit = NULL,
    @RunStamp datetime2 = NULL,
    @GeneratedAt datetime2 = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[AppealRecommendation]
    SET
        [SubjectKind] = ISNULL(@SubjectKind, [SubjectKind]),
        [ParcelID] = CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, [ParcelID]) END,
        [PropertyID] = CASE WHEN @PropertyID_Clear = 1 THEN NULL ELSE ISNULL(@PropertyID, [PropertyID]) END,
        [AssessmentYear] = ISNULL(@AssessmentYear, [AssessmentYear]),
        [MethodologyVersion] = ISNULL(@MethodologyVersion, [MethodologyVersion]),
        [IsCurrent] = ISNULL(@IsCurrent, [IsCurrent]),
        [CurrentAV] = CASE WHEN @CurrentAV_Clear = 1 THEN NULL ELSE ISNULL(@CurrentAV, [CurrentAV]) END,
        [PriorAVAsDetermined] = CASE WHEN @PriorAVAsDetermined_Clear = 1 THEN NULL ELSE ISNULL(@PriorAVAsDetermined, [PriorAVAsDetermined]) END,
        [UnitOfComparison] = CASE WHEN @UnitOfComparison_Clear = 1 THEN NULL ELSE ISNULL(@UnitOfComparison, [UnitOfComparison]) END,
        [Denominator] = CASE WHEN @Denominator_Clear = 1 THEN NULL ELSE ISNULL(@Denominator, [Denominator]) END,
        [DenominatorSource] = CASE WHEN @DenominatorSource_Clear = 1 THEN NULL ELSE ISNULL(@DenominatorSource, [DenominatorSource]) END,
        [DenominatorIsFallback] = ISNULL(@DenominatorIsFallback, [DenominatorIsFallback]),
        [ValueSignalCount] = ISNULL(@ValueSignalCount, [ValueSignalCount]),
        [IncreaseFlag] = ISNULL(@IncreaseFlag, [IncreaseFlag]),
        [FloorSupport] = ISNULL(@FloorSupport, [FloorSupport]),
        [PeerOutOfLine] = ISNULL(@PeerOutOfLine, [PeerOutOfLine]),
        [OwnSaleContrary] = ISNULL(@OwnSaleContrary, [OwnSaleContrary]),
        [Verdict] = ISNULL(@Verdict, [Verdict]),
        [NotAvailableReason] = CASE WHEN @NotAvailableReason_Clear = 1 THEN NULL ELSE ISNULL(@NotAvailableReason, [NotAvailableReason]) END,
        [ConfidenceTier] = CASE WHEN @ConfidenceTier_Clear = 1 THEN NULL ELSE ISNULL(@ConfidenceTier, [ConfidenceTier]) END,
        [FloorValue] = CASE WHEN @FloorValue_Clear = 1 THEN NULL ELSE ISNULL(@FloorValue, [FloorValue]) END,
        [AskValue] = CASE WHEN @AskValue_Clear = 1 THEN NULL ELSE ISNULL(@AskValue, [AskValue]) END,
        [AskPolicy] = ISNULL(@AskPolicy, [AskPolicy]),
        [AskBasis] = CASE WHEN @AskBasis_Clear = 1 THEN NULL ELSE ISNULL(@AskBasis, [AskBasis]) END,
        [EstSavingsAtAsk] = CASE WHEN @EstSavingsAtAsk_Clear = 1 THEN NULL ELSE ISNULL(@EstSavingsAtAsk, [EstSavingsAtAsk]) END,
        [EstSavingsAtFloor] = CASE WHEN @EstSavingsAtFloor_Clear = 1 THEN NULL ELSE ISNULL(@EstSavingsAtFloor, [EstSavingsAtFloor]) END,
        [EffectiveTaxRate] = CASE WHEN @EffectiveTaxRate_Clear = 1 THEN NULL ELSE ISNULL(@EffectiveTaxRate, [EffectiveTaxRate]) END,
        [GroupingStatus] = ISNULL(@GroupingStatus, [GroupingStatus]),
        [GroupingVersion] = CASE WHEN @GroupingVersion_Clear = 1 THEN NULL ELSE ISNULL(@GroupingVersion, [GroupingVersion]) END,
        [AlreadyAppealed] = ISNULL(@AlreadyAppealed, [AlreadyAppealed]),
        [ExistingRep] = CASE WHEN @ExistingRep_Clear = 1 THEN NULL ELSE ISNULL(@ExistingRep, [ExistingRep]) END,
        [Exempt] = ISNULL(@Exempt, [Exempt]),
        [BelowSavingsFloor] = ISNULL(@BelowSavingsFloor, [BelowSavingsFloor]),
        [RunStamp] = ISNULL(@RunStamp, [RunStamp]),
        [GeneratedAt] = ISNULL(@GeneratedAt, [GeneratedAt])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [indiana_tax].[vwAppealRecommendations] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [indiana_tax].[vwAppealRecommendations]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [indiana_tax].[spUpdateAppealRecommendation] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the AppealRecommendation table
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[trgUpdateAppealRecommendation]', 'TR') IS NOT NULL
    DROP TRIGGER [indiana_tax].[trgUpdateAppealRecommendation];
GO
CREATE TRIGGER [indiana_tax].trgUpdateAppealRecommendation
ON [indiana_tax].[AppealRecommendation]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[AppealRecommendation]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [indiana_tax].[AppealRecommendation] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for Appeal Recommendations */

GRANT EXECUTE ON [indiana_tax].[spUpdateAppealRecommendation] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for Appeal Recommendation Signals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendation Signals
-- Item: spDeleteAppealRecommendationSignal
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR AppealRecommendationSignal
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spDeleteAppealRecommendationSignal]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spDeleteAppealRecommendationSignal];
GO

CREATE PROCEDURE [indiana_tax].[spDeleteAppealRecommendationSignal]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [indiana_tax].[AppealRecommendationSignal]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [indiana_tax].[spDeleteAppealRecommendationSignal] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for Appeal Recommendation Signals */

GRANT EXECUTE ON [indiana_tax].[spDeleteAppealRecommendationSignal] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for Appeal Recommendations */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Recommendations
-- Item: spDeleteAppealRecommendation
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR AppealRecommendation
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spDeleteAppealRecommendation]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spDeleteAppealRecommendation];
GO

CREATE PROCEDURE [indiana_tax].[spDeleteAppealRecommendation]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [indiana_tax].[AppealRecommendation]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [indiana_tax].[spDeleteAppealRecommendation] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for Appeal Recommendations */

GRANT EXECUTE ON [indiana_tax].[spDeleteAppealRecommendation] TO [cdp_Developer], [cdp_Integration];

/* Index for Foreign Keys for SaleConveyanceMember */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key SaleConveyanceID in table SaleConveyanceMember
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_SaleConveyanceMember_SaleConveyanceID' 
    AND object_id = OBJECT_ID('[indiana_tax].[SaleConveyanceMember]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_SaleConveyanceMember_SaleConveyanceID ON [indiana_tax].[SaleConveyanceMember] ([SaleConveyanceID]);

-- Index for foreign key SaleTransactionID in table SaleConveyanceMember
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_SaleConveyanceMember_SaleTransactionID' 
    AND object_id = OBJECT_ID('[indiana_tax].[SaleConveyanceMember]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_SaleConveyanceMember_SaleTransactionID ON [indiana_tax].[SaleConveyanceMember] ([SaleTransactionID]);

-- Index for foreign key ParcelID in table SaleConveyanceMember
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_SaleConveyanceMember_ParcelID' 
    AND object_id = OBJECT_ID('[indiana_tax].[SaleConveyanceMember]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_SaleConveyanceMember_ParcelID ON [indiana_tax].[SaleConveyanceMember] ([ParcelID]);

/* Base View SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: vwSaleConveyanceMembers
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Sale Conveyance Members
-----               SCHEMA:      indiana_tax
-----               BASE TABLE:  SaleConveyanceMember
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[vwSaleConveyanceMembers]', 'V') IS NOT NULL
    DROP VIEW [indiana_tax].[vwSaleConveyanceMembers];
GO

CREATE VIEW [indiana_tax].[vwSaleConveyanceMembers]
AS
SELECT
    s.*,
    indianataxSaleConveyance_SaleConveyanceID.[ConveyanceKey] AS [SaleConveyance],
    indianataxSaleTransaction_SaleTransactionID.[SitusAddress] AS [SaleTransaction],
    indianataxParcel_ParcelID.[ParcelNumber] AS [Parcel]
FROM
    [indiana_tax].[SaleConveyanceMember] AS s
INNER JOIN
    [indiana_tax].[SaleConveyance] AS indianataxSaleConveyance_SaleConveyanceID
  ON
    [s].[SaleConveyanceID] = indianataxSaleConveyance_SaleConveyanceID.[ID]
INNER JOIN
    [indiana_tax].[SaleTransaction] AS indianataxSaleTransaction_SaleTransactionID
  ON
    [s].[SaleTransactionID] = indianataxSaleTransaction_SaleTransactionID.[ID]
LEFT OUTER JOIN
    [indiana_tax].[Parcel] AS indianataxParcel_ParcelID
  ON
    [s].[ParcelID] = indianataxParcel_ParcelID.[ID]
GO
GRANT SELECT ON [indiana_tax].[vwSaleConveyanceMembers] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: Permissions for vwSaleConveyanceMembers
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [indiana_tax].[vwSaleConveyanceMembers] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: spCreateSaleConveyanceMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR SaleConveyanceMember
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spCreateSaleConveyanceMember]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spCreateSaleConveyanceMember];
GO

CREATE PROCEDURE [indiana_tax].[spCreateSaleConveyanceMember]
    @ID uniqueidentifier = NULL,
    @SaleConveyanceID uniqueidentifier,
    @SaleTransactionID uniqueidentifier,
    @ParcelID_Clear bit = 0,
    @ParcelID uniqueidentifier = NULL,
    @MemberBuildingSqFt_Clear bit = 0,
    @MemberBuildingSqFt decimal(14, 2) = NULL,
    @MemberUnits_Clear bit = 0,
    @MemberUnits decimal(12, 2) = NULL,
    @MemberAcres_Clear bit = 0,
    @MemberAcres decimal(12, 4) = NULL,
    @ContributesSqFt bit,
    @IsDuplicateCard bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [indiana_tax].[SaleConveyanceMember]
            (
                [ID],
                [SaleConveyanceID],
                [SaleTransactionID],
                [ParcelID],
                [MemberBuildingSqFt],
                [MemberUnits],
                [MemberAcres],
                [ContributesSqFt],
                [IsDuplicateCard]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SaleConveyanceID,
                @SaleTransactionID,
                CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, NULL) END,
                CASE WHEN @MemberBuildingSqFt_Clear = 1 THEN NULL ELSE ISNULL(@MemberBuildingSqFt, NULL) END,
                CASE WHEN @MemberUnits_Clear = 1 THEN NULL ELSE ISNULL(@MemberUnits, NULL) END,
                CASE WHEN @MemberAcres_Clear = 1 THEN NULL ELSE ISNULL(@MemberAcres, NULL) END,
                @ContributesSqFt,
                ISNULL(@IsDuplicateCard, 0)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [indiana_tax].[SaleConveyanceMember]
            (
                [SaleConveyanceID],
                [SaleTransactionID],
                [ParcelID],
                [MemberBuildingSqFt],
                [MemberUnits],
                [MemberAcres],
                [ContributesSqFt],
                [IsDuplicateCard]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SaleConveyanceID,
                @SaleTransactionID,
                CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, NULL) END,
                CASE WHEN @MemberBuildingSqFt_Clear = 1 THEN NULL ELSE ISNULL(@MemberBuildingSqFt, NULL) END,
                CASE WHEN @MemberUnits_Clear = 1 THEN NULL ELSE ISNULL(@MemberUnits, NULL) END,
                CASE WHEN @MemberAcres_Clear = 1 THEN NULL ELSE ISNULL(@MemberAcres, NULL) END,
                @ContributesSqFt,
                ISNULL(@IsDuplicateCard, 0)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [indiana_tax].[vwSaleConveyanceMembers] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [indiana_tax].[spCreateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for Sale Conveyance Members */

GRANT EXECUTE ON [indiana_tax].[spCreateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: spUpdateSaleConveyanceMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR SaleConveyanceMember
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spUpdateSaleConveyanceMember]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spUpdateSaleConveyanceMember];
GO

CREATE PROCEDURE [indiana_tax].[spUpdateSaleConveyanceMember]
    @ID uniqueidentifier,
    @SaleConveyanceID uniqueidentifier = NULL,
    @SaleTransactionID uniqueidentifier = NULL,
    @ParcelID_Clear bit = 0,
    @ParcelID uniqueidentifier = NULL,
    @MemberBuildingSqFt_Clear bit = 0,
    @MemberBuildingSqFt decimal(14, 2) = NULL,
    @MemberUnits_Clear bit = 0,
    @MemberUnits decimal(12, 2) = NULL,
    @MemberAcres_Clear bit = 0,
    @MemberAcres decimal(12, 4) = NULL,
    @ContributesSqFt bit = NULL,
    @IsDuplicateCard bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[SaleConveyanceMember]
    SET
        [SaleConveyanceID] = ISNULL(@SaleConveyanceID, [SaleConveyanceID]),
        [SaleTransactionID] = ISNULL(@SaleTransactionID, [SaleTransactionID]),
        [ParcelID] = CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, [ParcelID]) END,
        [MemberBuildingSqFt] = CASE WHEN @MemberBuildingSqFt_Clear = 1 THEN NULL ELSE ISNULL(@MemberBuildingSqFt, [MemberBuildingSqFt]) END,
        [MemberUnits] = CASE WHEN @MemberUnits_Clear = 1 THEN NULL ELSE ISNULL(@MemberUnits, [MemberUnits]) END,
        [MemberAcres] = CASE WHEN @MemberAcres_Clear = 1 THEN NULL ELSE ISNULL(@MemberAcres, [MemberAcres]) END,
        [ContributesSqFt] = ISNULL(@ContributesSqFt, [ContributesSqFt]),
        [IsDuplicateCard] = ISNULL(@IsDuplicateCard, [IsDuplicateCard])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [indiana_tax].[vwSaleConveyanceMembers] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [indiana_tax].[vwSaleConveyanceMembers]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [indiana_tax].[spUpdateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the SaleConveyanceMember table
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[trgUpdateSaleConveyanceMember]', 'TR') IS NOT NULL
    DROP TRIGGER [indiana_tax].[trgUpdateSaleConveyanceMember];
GO
CREATE TRIGGER [indiana_tax].trgUpdateSaleConveyanceMember
ON [indiana_tax].[SaleConveyanceMember]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[SaleConveyanceMember]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [indiana_tax].[SaleConveyanceMember] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for Sale Conveyance Members */

GRANT EXECUTE ON [indiana_tax].[spUpdateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: spDeleteSaleConveyanceMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR SaleConveyanceMember
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spDeleteSaleConveyanceMember]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spDeleteSaleConveyanceMember];
GO

CREATE PROCEDURE [indiana_tax].[spDeleteSaleConveyanceMember]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [indiana_tax].[SaleConveyanceMember]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [indiana_tax].[spDeleteSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for Sale Conveyance Members */

GRANT EXECUTE ON [indiana_tax].[spDeleteSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET DefaultInView = 1
               WHERE ID = 'A73373E3-7D43-4364-8C72-E1EE9A953245'
               AND AutoUpdateDefaultInView = 1;

            UPDATE [${flyway:defaultSchema}].[Entity]
            SET AllowUserSearchAPI = 0
            WHERE ID = '04E37D72-B573-4B81-B1E1-A501F1372851'
            AND AutoUpdateAllowUserSearchAPI = 1;

/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '3B268226-3411-4D95-AC21-EABB8974894E'
               AND AutoUpdateDefaultInView = 1;

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'DD149791-D02E-43D5-A9AD-7628D5DA6DC4'
               AND AutoUpdateIncludeInUserSearchAPI = 1;

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET UserSearchPredicateAPI = 'Exact'
               WHERE ID = 'DD149791-D02E-43D5-A9AD-7628D5DA6DC4'
               AND AutoUpdateUserSearchPredicate = 1;

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET UserSearchPredicateAPI = 'Exact'
               WHERE ID = '3B447C2F-2045-4307-8FD7-708DA6946928'
               AND AutoUpdateUserSearchPredicate = 1;

/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'B5D1A3CF-6E50-4248-ADC9-D2EF231F1EF0'
               AND AutoUpdateIncludeInUserSearchAPI = 1;

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'B91BF5A2-84B3-4D39-9B5D-DCD36BE9436F'
               AND AutoUpdateIncludeInUserSearchAPI = 1;

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET UserSearchPredicateAPI = 'BeginsWith'
               WHERE ID = '87FF5BF2-7A33-49DD-A2F9-ECC759C1C9F5'
               AND AutoUpdateUserSearchPredicate = 1;

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET UserSearchPredicateAPI = 'Exact'
               WHERE ID = 'B5D1A3CF-6E50-4248-ADC9-D2EF231F1EF0'
               AND AutoUpdateUserSearchPredicate = 1;

/* Set categories for 14 fields */

-- UPDATE Entity Field Category Info Sale Conveyance Members.ID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'CABCFE03-7D3F-4FCE-A7BB-5E5A6609B84E' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.SaleConveyanceID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'BE39C785-0998-4B06-B8FD-4ECFF71B2172' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.SaleTransactionID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'FAFA9F38-6D24-4E0A-A38A-C6C072BD43A0' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.ParcelID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2890853E-689F-4B7B-B352-39CE4597ACC5' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.MemberBuildingSqFt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'FBDE08C2-E482-4DA5-8206-9F68B8AA38A8' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.MemberUnits 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'EC4FBCC2-C39D-49AA-928D-1D07AEF936D7' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.MemberAcres 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B06EA103-384F-47DB-BB04-0C4D7C75BB1D' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.ContributesSqFt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'A73373E3-7D43-4364-8C72-E1EE9A953245' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.IsDuplicateCard 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '8FC53A0E-32F3-42AD-8CA0-840BB7A39B43' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.SaleConveyance 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   Category = 'Related Data',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'CA092B55-B63A-4288-BB13-AC74E31175AF' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.SaleTransaction 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D60DD0AD-E7F9-4116-A01C-431EF5A01186' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.Parcel 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D3FFFCE6-1512-48F9-A289-4AEEEC652088' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.__mj_CreatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '19D9AE20-7B2D-4AEC-8ADF-CF226E77974B' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Sale Conveyance Members.__mj_UpdatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '7F7387BD-2F34-486C-98CA-61470F013CA9' AND AutoUpdateCategory = 1;

/* Set categories for 39 fields */

-- UPDATE Entity Field Category Info Appeal Recommendations.ID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D36178A9-BE15-41E3-8ABA-994D654F9286' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.SubjectKind 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '82566216-36B5-486A-87C4-8EA944D1EEE0' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.ParcelID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5DA3FB6B-C2BB-4631-B84A-86EB339008F4' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.PropertyID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '7B7BD624-2819-4C0D-ACDC-D0D9FAD5A244' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.AssessmentYear 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '3B447C2F-2045-4307-8FD7-708DA6946928' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.MethodologyVersion 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '3B268226-3411-4D95-AC21-EABB8974894E' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.IsCurrent 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Current',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '3A8C743F-F243-405C-AF16-5D87AC57DE6D' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.Parcel 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Parcel Name',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2E703110-8F1B-4BD4-B3FC-77CDCBCB411D' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.CurrentAV 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'C8F1055A-89CB-4AF5-84CF-EAE449B656FE' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.PriorAVAsDetermined 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Prior Year Assessed Value',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '488E00A0-4DFE-45E7-94C2-8F393C092989' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.UnitOfComparison 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0DE0D626-BB9A-4EF1-AE8C-9FBBCEF658C5' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.Denominator 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '8C167E71-B35F-4E9D-8BAD-03B8E738FAF9' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.DenominatorSource 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '71A6088B-8382-4EEF-99F2-BEEABEBF19AD' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.DenominatorIsFallback 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'A858CFA6-14B1-49FF-9380-6490C3BA2848' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.ValueSignalCount 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5E7E00DD-E6DD-456B-AF33-9B03E3989476' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.IncreaseFlag 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '7C719951-1441-4233-94E7-704C4014E712' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.FloorSupport 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '6BEA06C4-1320-4605-A4B4-17C81883060B' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.PeerOutOfLine 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '4C265896-3883-4043-8ED2-E24948C2126D' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.OwnSaleContrary 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'AE38E36A-EB87-4972-BB15-CB4442068757' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.Verdict 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'DD149791-D02E-43D5-A9AD-7628D5DA6DC4' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.NotAvailableReason 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D3B30128-6B07-47B3-96AE-068C22EAD751' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.ConfidenceTier 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D412626F-751F-44F7-A1B7-12BF6E980514' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.FloorValue 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'F2FBA8FF-0C41-48AE-9DDC-58ADACC7A7AA' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.AskValue 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'A48578E1-2B65-4240-AAD9-38C126CB744A' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.AskPolicy 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '1826970A-AE2B-4F20-AD92-6DF87139F37B' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.AskBasis 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'E894CCFB-C162-47E3-9762-3310825BC8F4' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.EstSavingsAtAsk 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Est. Savings at Ask',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '7BEAF931-37A6-46B3-8F68-770AD339D06D' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.EstSavingsAtFloor 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Est. Savings at Floor',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5787B0C7-94E9-4615-A6D3-275AD1870EFE' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.EffectiveTaxRate 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'C7AF0316-5A1E-4ABD-9CEB-0F8F317C5404' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.GroupingStatus 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '3CF4424D-82F5-44F7-8BAC-0D64AE748E0E' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.GroupingVersion 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '58AE8FFE-CD3C-45C6-8F1D-F3AC83298A9F' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.AlreadyAppealed 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '55E9CD80-1D4D-43F9-B0F7-7369A7ACB144' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.ExistingRep 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Existing Representative',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '9ADD4883-E629-4EA1-9905-185560BC19BE' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.Exempt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '8127FE50-3A5B-4264-B436-6650B0DCBB6B' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.BelowSavingsFloor 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '359EA202-0222-4576-9EFA-71F0B411AFA8' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.RunStamp 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'E940D1E6-8099-4B68-BEE2-AC8FA3332080' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.GeneratedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B939ADC8-DA98-4DC3-B655-05747611041A' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.__mj_CreatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D9AD157C-3BDB-4F7A-B0B8-5D2EAB2AEF62' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Recommendations.__mj_UpdatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'D1BAE6BF-2FA0-45AE-96C8-2DC44F15560E' AND AutoUpdateCategory = 1;

