/* SQL text to insert entity field value with ID d9a19243-770a-4ad3-b7b8-9f5620c83969 */
INSERT INTO [${flyway:defaultSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('d9a19243-770a-4ad3-b7b8-9f5620c83969', '905DBB07-BAAB-40F8-AB2F-9D79AAA65CE7', 3, '$/key', '$/key', GETUTCDATE(), GETUTCDATE());

/* SQL text to update entity field value sequence */
UPDATE [${flyway:defaultSchema}].[EntityFieldValue] SET Sequence=4 WHERE ID='AD6D807F-559C-4D6E-AFF2-5ECABAECD6E9';

/* SQL text to update virtual entity field UnverifiedCompCount for entity Store Analysis */
UPDATE
                                    [${flyway:defaultSchema}].[EntityField]
                                  SET
                                    Sequence=70,
                                    Type='int',
                                    AllowsNull=1,
                                    
                                    Length=4,
                                    Precision=10,
                                    Scale=0
                                  WHERE
                                    ID = '377D324C-20CB-4A76-AB06-CB439830F01E';

/* Index for Foreign Keys for ComparableAssessmentSet */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comparable Assessment Sets
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key SubjectParcelID in table ComparableAssessmentSet
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ComparableAssessmentSet_SubjectParcelID' 
    AND object_id = OBJECT_ID('[indiana_tax].[ComparableAssessmentSet]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ComparableAssessmentSet_SubjectParcelID ON [indiana_tax].[ComparableAssessmentSet] ([SubjectParcelID]);

/* Base View SQL for Comparable Assessment Sets */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comparable Assessment Sets
-- Item: vwComparableAssessmentSets
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Comparable Assessment Sets
-----               SCHEMA:      indiana_tax
-----               BASE TABLE:  ComparableAssessmentSet
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[vwComparableAssessmentSets]', 'V') IS NOT NULL
    DROP VIEW [indiana_tax].[vwComparableAssessmentSets];
GO

CREATE VIEW [indiana_tax].[vwComparableAssessmentSets]
AS
SELECT
    c.*,
    indianataxParcel_SubjectParcelID.[ParcelNumber] AS [SubjectParcel]
FROM
    [indiana_tax].[ComparableAssessmentSet] AS c
INNER JOIN
    [indiana_tax].[Parcel] AS indianataxParcel_SubjectParcelID
  ON
    [c].[SubjectParcelID] = indianataxParcel_SubjectParcelID.[ID]
GO
GRANT SELECT ON [indiana_tax].[vwComparableAssessmentSets] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for Comparable Assessment Sets */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comparable Assessment Sets
-- Item: Permissions for vwComparableAssessmentSets
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [indiana_tax].[vwComparableAssessmentSets] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for Comparable Assessment Sets */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comparable Assessment Sets
-- Item: spCreateComparableAssessmentSet
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ComparableAssessmentSet
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spCreateComparableAssessmentSet]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spCreateComparableAssessmentSet];
GO

CREATE PROCEDURE [indiana_tax].[spCreateComparableAssessmentSet]
    @ID uniqueidentifier = NULL,
    @SubjectParcelID uniqueidentifier,
    @FocusYear smallint,
    @MethodologyVersion nvarchar(30),
    @PropertyTypeGroup_Clear bit = 0,
    @PropertyTypeGroup nvarchar(30) = NULL,
    @UnitOfComparison nvarchar(10),
    @HeadlineTrack nvarchar(10) = NULL,
    @SubjectDenomValue_Clear bit = 0,
    @SubjectDenomValue decimal(14, 2) = NULL,
    @SubjectOriginalAV_Clear bit = 0,
    @SubjectOriginalAV decimal(14, 2) = NULL,
    @SubjectEffectiveAV_Clear bit = 0,
    @SubjectEffectiveAV decimal(14, 2) = NULL,
    @SubjectPerUnitEffective_Clear bit = 0,
    @SubjectPerUnitEffective decimal(14, 2) = NULL,
    @NeighborhoodCode_Clear bit = 0,
    @NeighborhoodCode nvarchar(120) = NULL,
    @NeighborhoodCompCount_Clear bit = 0,
    @NeighborhoodCompCount int = NULL,
    @NeighborhoodMeanPerUnit_Clear bit = 0,
    @NeighborhoodMeanPerUnit decimal(14, 2) = NULL,
    @NeighborhoodMedianPerUnit_Clear bit = 0,
    @NeighborhoodMedianPerUnit decimal(14, 2) = NULL,
    @CountyCompCount_Clear bit = 0,
    @CountyCompCount int = NULL,
    @CountyMeanPerUnit_Clear bit = 0,
    @CountyMeanPerUnit decimal(14, 2) = NULL,
    @CountyMedianPerUnit_Clear bit = 0,
    @CountyMedianPerUnit decimal(14, 2) = NULL,
    @SubjectPercentile_Clear bit = 0,
    @SubjectPercentile smallint = NULL,
    @Status nvarchar(10) = NULL,
    @AnalystNote_Clear bit = 0,
    @AnalystNote nvarchar(MAX) = NULL,
    @GeneratedAt_Clear bit = 0,
    @GeneratedAt datetimeoffset = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [indiana_tax].[ComparableAssessmentSet]
            (
                [ID],
                [SubjectParcelID],
                [FocusYear],
                [MethodologyVersion],
                [PropertyTypeGroup],
                [UnitOfComparison],
                [HeadlineTrack],
                [SubjectDenomValue],
                [SubjectOriginalAV],
                [SubjectEffectiveAV],
                [SubjectPerUnitEffective],
                [NeighborhoodCode],
                [NeighborhoodCompCount],
                [NeighborhoodMeanPerUnit],
                [NeighborhoodMedianPerUnit],
                [CountyCompCount],
                [CountyMeanPerUnit],
                [CountyMedianPerUnit],
                [SubjectPercentile],
                [Status],
                [AnalystNote],
                [GeneratedAt]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SubjectParcelID,
                @FocusYear,
                @MethodologyVersion,
                CASE WHEN @PropertyTypeGroup_Clear = 1 THEN NULL ELSE ISNULL(@PropertyTypeGroup, NULL) END,
                @UnitOfComparison,
                ISNULL(@HeadlineTrack, 'Effective'),
                CASE WHEN @SubjectDenomValue_Clear = 1 THEN NULL ELSE ISNULL(@SubjectDenomValue, NULL) END,
                CASE WHEN @SubjectOriginalAV_Clear = 1 THEN NULL ELSE ISNULL(@SubjectOriginalAV, NULL) END,
                CASE WHEN @SubjectEffectiveAV_Clear = 1 THEN NULL ELSE ISNULL(@SubjectEffectiveAV, NULL) END,
                CASE WHEN @SubjectPerUnitEffective_Clear = 1 THEN NULL ELSE ISNULL(@SubjectPerUnitEffective, NULL) END,
                CASE WHEN @NeighborhoodCode_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodCode, NULL) END,
                CASE WHEN @NeighborhoodCompCount_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodCompCount, NULL) END,
                CASE WHEN @NeighborhoodMeanPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodMeanPerUnit, NULL) END,
                CASE WHEN @NeighborhoodMedianPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodMedianPerUnit, NULL) END,
                CASE WHEN @CountyCompCount_Clear = 1 THEN NULL ELSE ISNULL(@CountyCompCount, NULL) END,
                CASE WHEN @CountyMeanPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@CountyMeanPerUnit, NULL) END,
                CASE WHEN @CountyMedianPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@CountyMedianPerUnit, NULL) END,
                CASE WHEN @SubjectPercentile_Clear = 1 THEN NULL ELSE ISNULL(@SubjectPercentile, NULL) END,
                ISNULL(@Status, 'Draft'),
                CASE WHEN @AnalystNote_Clear = 1 THEN NULL ELSE ISNULL(@AnalystNote, NULL) END,
                CASE WHEN @GeneratedAt_Clear = 1 THEN NULL ELSE ISNULL(@GeneratedAt, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [indiana_tax].[ComparableAssessmentSet]
            (
                [SubjectParcelID],
                [FocusYear],
                [MethodologyVersion],
                [PropertyTypeGroup],
                [UnitOfComparison],
                [HeadlineTrack],
                [SubjectDenomValue],
                [SubjectOriginalAV],
                [SubjectEffectiveAV],
                [SubjectPerUnitEffective],
                [NeighborhoodCode],
                [NeighborhoodCompCount],
                [NeighborhoodMeanPerUnit],
                [NeighborhoodMedianPerUnit],
                [CountyCompCount],
                [CountyMeanPerUnit],
                [CountyMedianPerUnit],
                [SubjectPercentile],
                [Status],
                [AnalystNote],
                [GeneratedAt]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SubjectParcelID,
                @FocusYear,
                @MethodologyVersion,
                CASE WHEN @PropertyTypeGroup_Clear = 1 THEN NULL ELSE ISNULL(@PropertyTypeGroup, NULL) END,
                @UnitOfComparison,
                ISNULL(@HeadlineTrack, 'Effective'),
                CASE WHEN @SubjectDenomValue_Clear = 1 THEN NULL ELSE ISNULL(@SubjectDenomValue, NULL) END,
                CASE WHEN @SubjectOriginalAV_Clear = 1 THEN NULL ELSE ISNULL(@SubjectOriginalAV, NULL) END,
                CASE WHEN @SubjectEffectiveAV_Clear = 1 THEN NULL ELSE ISNULL(@SubjectEffectiveAV, NULL) END,
                CASE WHEN @SubjectPerUnitEffective_Clear = 1 THEN NULL ELSE ISNULL(@SubjectPerUnitEffective, NULL) END,
                CASE WHEN @NeighborhoodCode_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodCode, NULL) END,
                CASE WHEN @NeighborhoodCompCount_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodCompCount, NULL) END,
                CASE WHEN @NeighborhoodMeanPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodMeanPerUnit, NULL) END,
                CASE WHEN @NeighborhoodMedianPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodMedianPerUnit, NULL) END,
                CASE WHEN @CountyCompCount_Clear = 1 THEN NULL ELSE ISNULL(@CountyCompCount, NULL) END,
                CASE WHEN @CountyMeanPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@CountyMeanPerUnit, NULL) END,
                CASE WHEN @CountyMedianPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@CountyMedianPerUnit, NULL) END,
                CASE WHEN @SubjectPercentile_Clear = 1 THEN NULL ELSE ISNULL(@SubjectPercentile, NULL) END,
                ISNULL(@Status, 'Draft'),
                CASE WHEN @AnalystNote_Clear = 1 THEN NULL ELSE ISNULL(@AnalystNote, NULL) END,
                CASE WHEN @GeneratedAt_Clear = 1 THEN NULL ELSE ISNULL(@GeneratedAt, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [indiana_tax].[vwComparableAssessmentSets] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [indiana_tax].[spCreateComparableAssessmentSet] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for Comparable Assessment Sets */

GRANT EXECUTE ON [indiana_tax].[spCreateComparableAssessmentSet] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for Comparable Assessment Sets */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comparable Assessment Sets
-- Item: spUpdateComparableAssessmentSet
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ComparableAssessmentSet
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spUpdateComparableAssessmentSet]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spUpdateComparableAssessmentSet];
GO

CREATE PROCEDURE [indiana_tax].[spUpdateComparableAssessmentSet]
    @ID uniqueidentifier,
    @SubjectParcelID uniqueidentifier = NULL,
    @FocusYear smallint = NULL,
    @MethodologyVersion nvarchar(30) = NULL,
    @PropertyTypeGroup_Clear bit = 0,
    @PropertyTypeGroup nvarchar(30) = NULL,
    @UnitOfComparison nvarchar(10) = NULL,
    @HeadlineTrack nvarchar(10) = NULL,
    @SubjectDenomValue_Clear bit = 0,
    @SubjectDenomValue decimal(14, 2) = NULL,
    @SubjectOriginalAV_Clear bit = 0,
    @SubjectOriginalAV decimal(14, 2) = NULL,
    @SubjectEffectiveAV_Clear bit = 0,
    @SubjectEffectiveAV decimal(14, 2) = NULL,
    @SubjectPerUnitEffective_Clear bit = 0,
    @SubjectPerUnitEffective decimal(14, 2) = NULL,
    @NeighborhoodCode_Clear bit = 0,
    @NeighborhoodCode nvarchar(120) = NULL,
    @NeighborhoodCompCount_Clear bit = 0,
    @NeighborhoodCompCount int = NULL,
    @NeighborhoodMeanPerUnit_Clear bit = 0,
    @NeighborhoodMeanPerUnit decimal(14, 2) = NULL,
    @NeighborhoodMedianPerUnit_Clear bit = 0,
    @NeighborhoodMedianPerUnit decimal(14, 2) = NULL,
    @CountyCompCount_Clear bit = 0,
    @CountyCompCount int = NULL,
    @CountyMeanPerUnit_Clear bit = 0,
    @CountyMeanPerUnit decimal(14, 2) = NULL,
    @CountyMedianPerUnit_Clear bit = 0,
    @CountyMedianPerUnit decimal(14, 2) = NULL,
    @SubjectPercentile_Clear bit = 0,
    @SubjectPercentile smallint = NULL,
    @Status nvarchar(10) = NULL,
    @AnalystNote_Clear bit = 0,
    @AnalystNote nvarchar(MAX) = NULL,
    @GeneratedAt_Clear bit = 0,
    @GeneratedAt datetimeoffset = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[ComparableAssessmentSet]
    SET
        [SubjectParcelID] = ISNULL(@SubjectParcelID, [SubjectParcelID]),
        [FocusYear] = ISNULL(@FocusYear, [FocusYear]),
        [MethodologyVersion] = ISNULL(@MethodologyVersion, [MethodologyVersion]),
        [PropertyTypeGroup] = CASE WHEN @PropertyTypeGroup_Clear = 1 THEN NULL ELSE ISNULL(@PropertyTypeGroup, [PropertyTypeGroup]) END,
        [UnitOfComparison] = ISNULL(@UnitOfComparison, [UnitOfComparison]),
        [HeadlineTrack] = ISNULL(@HeadlineTrack, [HeadlineTrack]),
        [SubjectDenomValue] = CASE WHEN @SubjectDenomValue_Clear = 1 THEN NULL ELSE ISNULL(@SubjectDenomValue, [SubjectDenomValue]) END,
        [SubjectOriginalAV] = CASE WHEN @SubjectOriginalAV_Clear = 1 THEN NULL ELSE ISNULL(@SubjectOriginalAV, [SubjectOriginalAV]) END,
        [SubjectEffectiveAV] = CASE WHEN @SubjectEffectiveAV_Clear = 1 THEN NULL ELSE ISNULL(@SubjectEffectiveAV, [SubjectEffectiveAV]) END,
        [SubjectPerUnitEffective] = CASE WHEN @SubjectPerUnitEffective_Clear = 1 THEN NULL ELSE ISNULL(@SubjectPerUnitEffective, [SubjectPerUnitEffective]) END,
        [NeighborhoodCode] = CASE WHEN @NeighborhoodCode_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodCode, [NeighborhoodCode]) END,
        [NeighborhoodCompCount] = CASE WHEN @NeighborhoodCompCount_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodCompCount, [NeighborhoodCompCount]) END,
        [NeighborhoodMeanPerUnit] = CASE WHEN @NeighborhoodMeanPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodMeanPerUnit, [NeighborhoodMeanPerUnit]) END,
        [NeighborhoodMedianPerUnit] = CASE WHEN @NeighborhoodMedianPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@NeighborhoodMedianPerUnit, [NeighborhoodMedianPerUnit]) END,
        [CountyCompCount] = CASE WHEN @CountyCompCount_Clear = 1 THEN NULL ELSE ISNULL(@CountyCompCount, [CountyCompCount]) END,
        [CountyMeanPerUnit] = CASE WHEN @CountyMeanPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@CountyMeanPerUnit, [CountyMeanPerUnit]) END,
        [CountyMedianPerUnit] = CASE WHEN @CountyMedianPerUnit_Clear = 1 THEN NULL ELSE ISNULL(@CountyMedianPerUnit, [CountyMedianPerUnit]) END,
        [SubjectPercentile] = CASE WHEN @SubjectPercentile_Clear = 1 THEN NULL ELSE ISNULL(@SubjectPercentile, [SubjectPercentile]) END,
        [Status] = ISNULL(@Status, [Status]),
        [AnalystNote] = CASE WHEN @AnalystNote_Clear = 1 THEN NULL ELSE ISNULL(@AnalystNote, [AnalystNote]) END,
        [GeneratedAt] = CASE WHEN @GeneratedAt_Clear = 1 THEN NULL ELSE ISNULL(@GeneratedAt, [GeneratedAt]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [indiana_tax].[vwComparableAssessmentSets] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [indiana_tax].[vwComparableAssessmentSets]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [indiana_tax].[spUpdateComparableAssessmentSet] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ComparableAssessmentSet table
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[trgUpdateComparableAssessmentSet]', 'TR') IS NOT NULL
    DROP TRIGGER [indiana_tax].[trgUpdateComparableAssessmentSet];
GO
CREATE TRIGGER [indiana_tax].trgUpdateComparableAssessmentSet
ON [indiana_tax].[ComparableAssessmentSet]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[ComparableAssessmentSet]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [indiana_tax].[ComparableAssessmentSet] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for Comparable Assessment Sets */

GRANT EXECUTE ON [indiana_tax].[spUpdateComparableAssessmentSet] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for Comparable Assessment Sets */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comparable Assessment Sets
-- Item: spDeleteComparableAssessmentSet
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ComparableAssessmentSet
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spDeleteComparableAssessmentSet]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spDeleteComparableAssessmentSet];
GO

CREATE PROCEDURE [indiana_tax].[spDeleteComparableAssessmentSet]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [indiana_tax].[ComparableAssessmentSet]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [indiana_tax].[spDeleteComparableAssessmentSet] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for Comparable Assessment Sets */

GRANT EXECUTE ON [indiana_tax].[spDeleteComparableAssessmentSet] TO [cdp_Developer], [cdp_Integration];

/* SQL text to update entity field related entity name field map for entity field ID BE39C785-0998-4B06-B8FD-4ECFF71B2172 */
EXEC [${flyway:defaultSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='BE39C785-0998-4B06-B8FD-4ECFF71B2172', @RelatedEntityNameFieldMap='SaleConveyance';

/* Base View SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: vwSaleConveyanceMembers
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Sale Conveyance Members
-----               SCHEMA:      indiana_tax
-----               BASE TABLE:  SaleConveyanceMember
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[vwSaleConveyanceMembers]', 'V') IS NOT NULL
    DROP VIEW [indiana_tax].[vwSaleConveyanceMembers];
GO

CREATE VIEW [indiana_tax].[vwSaleConveyanceMembers]
AS
SELECT
    s.*,
    indianataxSaleConveyance_SaleConveyanceID.[ConveyanceKey] AS [SaleConveyance],
    indianataxSaleTransaction_SaleTransactionID.[SitusAddress] AS [SaleTransaction],
    indianataxParcel_ParcelID.[ParcelNumber] AS [Parcel]
FROM
    [indiana_tax].[SaleConveyanceMember] AS s
INNER JOIN
    [indiana_tax].[SaleConveyance] AS indianataxSaleConveyance_SaleConveyanceID
  ON
    [s].[SaleConveyanceID] = indianataxSaleConveyance_SaleConveyanceID.[ID]
INNER JOIN
    [indiana_tax].[SaleTransaction] AS indianataxSaleTransaction_SaleTransactionID
  ON
    [s].[SaleTransactionID] = indianataxSaleTransaction_SaleTransactionID.[ID]
LEFT OUTER JOIN
    [indiana_tax].[Parcel] AS indianataxParcel_ParcelID
  ON
    [s].[ParcelID] = indianataxParcel_ParcelID.[ID]
GO
GRANT SELECT ON [indiana_tax].[vwSaleConveyanceMembers] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: Permissions for vwSaleConveyanceMembers
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [indiana_tax].[vwSaleConveyanceMembers] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: spCreateSaleConveyanceMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR SaleConveyanceMember
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spCreateSaleConveyanceMember]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spCreateSaleConveyanceMember];
GO

CREATE PROCEDURE [indiana_tax].[spCreateSaleConveyanceMember]
    @ID uniqueidentifier = NULL,
    @SaleConveyanceID uniqueidentifier,
    @SaleTransactionID uniqueidentifier,
    @ParcelID_Clear bit = 0,
    @ParcelID uniqueidentifier = NULL,
    @MemberBuildingSqFt_Clear bit = 0,
    @MemberBuildingSqFt decimal(14, 2) = NULL,
    @MemberUnits_Clear bit = 0,
    @MemberUnits decimal(12, 2) = NULL,
    @MemberAcres_Clear bit = 0,
    @MemberAcres decimal(12, 4) = NULL,
    @ContributesSqFt bit,
    @IsDuplicateCard bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [indiana_tax].[SaleConveyanceMember]
            (
                [ID],
                [SaleConveyanceID],
                [SaleTransactionID],
                [ParcelID],
                [MemberBuildingSqFt],
                [MemberUnits],
                [MemberAcres],
                [ContributesSqFt],
                [IsDuplicateCard]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SaleConveyanceID,
                @SaleTransactionID,
                CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, NULL) END,
                CASE WHEN @MemberBuildingSqFt_Clear = 1 THEN NULL ELSE ISNULL(@MemberBuildingSqFt, NULL) END,
                CASE WHEN @MemberUnits_Clear = 1 THEN NULL ELSE ISNULL(@MemberUnits, NULL) END,
                CASE WHEN @MemberAcres_Clear = 1 THEN NULL ELSE ISNULL(@MemberAcres, NULL) END,
                @ContributesSqFt,
                ISNULL(@IsDuplicateCard, 0)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [indiana_tax].[SaleConveyanceMember]
            (
                [SaleConveyanceID],
                [SaleTransactionID],
                [ParcelID],
                [MemberBuildingSqFt],
                [MemberUnits],
                [MemberAcres],
                [ContributesSqFt],
                [IsDuplicateCard]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SaleConveyanceID,
                @SaleTransactionID,
                CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, NULL) END,
                CASE WHEN @MemberBuildingSqFt_Clear = 1 THEN NULL ELSE ISNULL(@MemberBuildingSqFt, NULL) END,
                CASE WHEN @MemberUnits_Clear = 1 THEN NULL ELSE ISNULL(@MemberUnits, NULL) END,
                CASE WHEN @MemberAcres_Clear = 1 THEN NULL ELSE ISNULL(@MemberAcres, NULL) END,
                @ContributesSqFt,
                ISNULL(@IsDuplicateCard, 0)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [indiana_tax].[vwSaleConveyanceMembers] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [indiana_tax].[spCreateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for Sale Conveyance Members */

GRANT EXECUTE ON [indiana_tax].[spCreateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: spUpdateSaleConveyanceMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR SaleConveyanceMember
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spUpdateSaleConveyanceMember]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spUpdateSaleConveyanceMember];
GO

CREATE PROCEDURE [indiana_tax].[spUpdateSaleConveyanceMember]
    @ID uniqueidentifier,
    @SaleConveyanceID uniqueidentifier = NULL,
    @SaleTransactionID uniqueidentifier = NULL,
    @ParcelID_Clear bit = 0,
    @ParcelID uniqueidentifier = NULL,
    @MemberBuildingSqFt_Clear bit = 0,
    @MemberBuildingSqFt decimal(14, 2) = NULL,
    @MemberUnits_Clear bit = 0,
    @MemberUnits decimal(12, 2) = NULL,
    @MemberAcres_Clear bit = 0,
    @MemberAcres decimal(12, 4) = NULL,
    @ContributesSqFt bit = NULL,
    @IsDuplicateCard bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[SaleConveyanceMember]
    SET
        [SaleConveyanceID] = ISNULL(@SaleConveyanceID, [SaleConveyanceID]),
        [SaleTransactionID] = ISNULL(@SaleTransactionID, [SaleTransactionID]),
        [ParcelID] = CASE WHEN @ParcelID_Clear = 1 THEN NULL ELSE ISNULL(@ParcelID, [ParcelID]) END,
        [MemberBuildingSqFt] = CASE WHEN @MemberBuildingSqFt_Clear = 1 THEN NULL ELSE ISNULL(@MemberBuildingSqFt, [MemberBuildingSqFt]) END,
        [MemberUnits] = CASE WHEN @MemberUnits_Clear = 1 THEN NULL ELSE ISNULL(@MemberUnits, [MemberUnits]) END,
        [MemberAcres] = CASE WHEN @MemberAcres_Clear = 1 THEN NULL ELSE ISNULL(@MemberAcres, [MemberAcres]) END,
        [ContributesSqFt] = ISNULL(@ContributesSqFt, [ContributesSqFt]),
        [IsDuplicateCard] = ISNULL(@IsDuplicateCard, [IsDuplicateCard])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [indiana_tax].[vwSaleConveyanceMembers] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [indiana_tax].[vwSaleConveyanceMembers]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [indiana_tax].[spUpdateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the SaleConveyanceMember table
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[trgUpdateSaleConveyanceMember]', 'TR') IS NOT NULL
    DROP TRIGGER [indiana_tax].[trgUpdateSaleConveyanceMember];
GO
CREATE TRIGGER [indiana_tax].trgUpdateSaleConveyanceMember
ON [indiana_tax].[SaleConveyanceMember]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[SaleConveyanceMember]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [indiana_tax].[SaleConveyanceMember] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for Sale Conveyance Members */

GRANT EXECUTE ON [indiana_tax].[spUpdateSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for Sale Conveyance Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Sale Conveyance Members
-- Item: spDeleteSaleConveyanceMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR SaleConveyanceMember
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spDeleteSaleConveyanceMember]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spDeleteSaleConveyanceMember];
GO

CREATE PROCEDURE [indiana_tax].[spDeleteSaleConveyanceMember]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [indiana_tax].[SaleConveyanceMember]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [indiana_tax].[spDeleteSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for Sale Conveyance Members */

GRANT EXECUTE ON [indiana_tax].[spDeleteSaleConveyanceMember] TO [cdp_Developer], [cdp_Integration];

/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET DefaultInView = 1
               WHERE ID = 'F7A39988-FE91-459C-A1EE-3D493B8BC105'
               AND AutoUpdateDefaultInView = 1;

