/* ============================================================================
   Indiana Property Tax Expert — the form columns take only the seven forms
   v5.58.x (companion to V202609130725 Indiana_Tax_Revision_Form)

   ReasonForm, NoteForm and RevisionForm hold an Indiana appeal-cycle form
   number that the parser recognises: 113 notice of assessment change, 115
   PTABOA determination, 130 petition to the county board, 131 IBTR appeal,
   133 correction of error, 134 preliminary informal-conference agreement,
   136 exemption application. The CHECK pins that set, so widening it (a card
   that cites Form 122 or 118 -- both occur in Lake's Reason For Change cells
   and are deliberately not parsed) is a migration, not a silent drift.
   Observed on apply: CodeGen derives no value list from a numeric IN list
   (ValueListType stays 'None', no EntityFieldValue rows), so the dropdown a
   string CHECK would have produced does not appear; the filter is by number.
   No data change: every value the loader writes is already in the set.
   ============================================================================ */

ALTER TABLE indiana_tax.CardValuationColumn ADD
    CONSTRAINT CK_CardValuationColumn_ReasonForm CHECK (ReasonForm IN (113, 115, 130, 131, 133, 134, 136));
GO

ALTER TABLE indiana_tax.CardNote ADD
    CONSTRAINT CK_CardNote_NoteForm CHECK (NoteForm IN (113, 115, 130, 131, 133, 134, 136));
GO

ALTER TABLE indiana_tax.Assessment ADD
    CONSTRAINT CK_Assessment_RevisionForm CHECK (RevisionForm IN (113, 115, 130, 131, 133, 134, 136));
GO

ALTER TABLE indiana_tax.CountyAssessorRecord ADD
    CONSTRAINT CK_CountyAssessorRecord_RevisionForm CHECK (RevisionForm IN (113, 115, 130, 131, 133, 134, 136));
GO


















































/* ============================================================================
   EVERYTHING BELOW WAS GENERATED BY THE MEMBERJUNCTION CODEGEN TOOL.
   CodeGen produced no statements for this migration: a numeric CHECK IN list
   yields no EntityFieldValue rows and changes no view or procedure. Its run
   file (CodeGen_Run_2026-09-13_14-21-37.sql) carried only unrelated output --
   another session's IBTR_Decisions entities (V202609130917) and the
   pre-existing "Store Analysis" EntityField sequence update -- excluded here;
   the run file is left in place for that session.
   ============================================================================ */
