-- The analyst's per-comp curation for one analysis's Sales tab.
-- Spec: Indiana_Tax_Expert/docs/proposals/2026-09-15-sales-comp-workbench-design.md §4.

CREATE TABLE indiana_tax.AppealAnalysisCompDecision (
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    AppealAnalysisID UNIQUEIDENTIFIER NOT NULL,
    SaleTransactionID UNIQUEIDENTIFIER NOT NULL,
    IsIncluded BIT NOT NULL CONSTRAINT DF_AppealAnalysisCompDecision_IsIncluded DEFAULT (1),
    SortOrder INT NULL,
    CONSTRAINT PK_AppealAnalysisCompDecision PRIMARY KEY (ID),
    CONSTRAINT FK_AppealAnalysisCompDecision_Analysis FOREIGN KEY (AppealAnalysisID) REFERENCES indiana_tax.AppealAnalysis (ID),
    CONSTRAINT FK_AppealAnalysisCompDecision_SaleTransaction FOREIGN KEY (SaleTransactionID) REFERENCES indiana_tax.SaleTransaction (ID),
    CONSTRAINT UQ_AppealAnalysisCompDecision UNIQUE (AppealAnalysisID, SaleTransactionID)
);

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The analyst''s curation of one candidate sale comp within one analysis: included/excluded and manual sort order. Keyed on SaleTransactionID, not ValuationComp.ID, because ValuationComp rows are deleted and regenerated wholesale on every batch run (build-valuation-comps.js); SaleTransactionID is stable. A decision with no matching comp in the current candidate pool is simply unused, not an error.', @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'AppealAnalysisCompDecision';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'True = included in the sales indication; false = available in the candidate pool but excluded by the analyst. No row for a given comp means "follow the batch''s own IsSelected default".', @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'AppealAnalysisCompDecision', @level2type = N'COLUMN', @level2name = N'IsIncluded';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Manual position among included comps. NULL means "follow the batch''s own SimilarityRank".', @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'AppealAnalysisCompDecision', @level2type = N'COLUMN', @level2name = N'SortOrder';


















































/* ============================================================================
   EVERYTHING BELOW WAS GENERATED BY THE MEMBERJUNCTION CODEGEN TOOL.
   It contains: the Entity/EntityField/EntityRelationship inserts, permission
   grants, the vwAppealAnalysisCompDecisions base view, spCreate/spUpdate/
   spDelete procedures, foreign-key indexes, and the AI-generated form-layout
   metadata (field categories, entity icon, DefaultForNewUser) for the one
   table in this migration: AppealAnalysisCompDecision.

   DO NOT EDIT BY HAND. If the hand-written DDL above changes, re-run CodeGen
   and replace this entire section.

   Source: CodeGen_Run_2026-09-16_10-55-50.sql, produced by `mj codegen`
   against a worktree database that already carried unrelated schema work
   from other Indiana Tax branches (IBTR Decision Citations, Legal Authority
   Chunks, Legal Authority Sections -- full base views, CRUD procedures, and
   full-text search objects) that this branch's checked-out code had not yet
   caught up to, plus one pre-existing, unrelated EntityField sequence fix
   for the "Store Analysis" entity (the same drift the prior migration,
   V202609142200__v5.59.x__Indiana_Tax_AppealAnalysis.sql, also excluded).
   All such unrelated regeneration was excluded from what follows (each
   excision point is marked inline below).
   ============================================================================ */

/* SQL generated to create new entity Appeal Analysis Comp Decisions */

      INSERT INTO [__mj].[Entity] (
         [ID],
         [Name],
         [DisplayName],
         [Description],
         [NameSuffix],
         [BaseTable],
         [BaseView],
         [SchemaName],
         [IncludeInAPI],
         [AllowUserSearchAPI],
         [AllowCaching]
         , [TrackRecordChanges]
         , [AuditRecordAccess]
         , [AuditViewRuns]
         , [AllowAllRowsAPI]
         , [AllowCreateAPI]
         , [AllowUpdateAPI]
         , [AllowDeleteAPI]
         , [UserViewMaxRows]
         , [__mj_CreatedAt]
         , [__mj_UpdatedAt]
      )
      VALUES (
         '2e095c07-db60-4924-b3fa-24fc88c7d5ae',
         'Appeal Analysis Comp Decisions',
         NULL,
         'The analyst''s curation of one candidate sale comp within one analysis: included/excluded and manual sort order. Keyed on SaleTransactionID, not ValuationComp.ID, because ValuationComp rows are deleted and regenerated wholesale on every batch run (build-valuation-comps.js); SaleTransactionID is stable. A decision with no matching comp in the current candidate pool is simply unused, not an error.',
         NULL,
         'AppealAnalysisCompDecision',
         'vwAppealAnalysisCompDecisions',
         'indiana_tax',
         1,
         1,
         0
         , 1
         , 0
         , 0
         , 0
         , 1
         , 1
         , 1
         , 1000
         , GETUTCDATE()
         , GETUTCDATE()
      );

/* SQL generated to add new entity Appeal Analysis Comp Decisions to application ID: '49E87630-494F-460F-8CF4-724B96F0F8B3' */
INSERT INTO [__mj].[ApplicationEntity]
                                       ([ApplicationID], [EntityID], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                       ('49E87630-494F-460F-8CF4-724B96F0F8B3', '2e095c07-db60-4924-b3fa-24fc88c7d5ae', (SELECT COALESCE(MAX([Sequence]),0)+1 FROM [__mj].[ApplicationEntity] WHERE [ApplicationID] = '49E87630-494F-460F-8CF4-724B96F0F8B3'), GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity Appeal Analysis Comp Decisions for role UI */
INSERT INTO [__mj].[EntityPermission]
                                                   ([EntityID], [RoleID], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                                   ('2e095c07-db60-4924-b3fa-24fc88c7d5ae', 'E0AFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 0, 0, 0, GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity Appeal Analysis Comp Decisions for role Developer */
INSERT INTO [__mj].[EntityPermission]
                                                   ([EntityID], [RoleID], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                                   ('2e095c07-db60-4924-b3fa-24fc88c7d5ae', 'DEAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity Appeal Analysis Comp Decisions for role Integration */
INSERT INTO [__mj].[EntityPermission]
                                                   ([EntityID], [RoleID], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                                   ('2e095c07-db60-4924-b3fa-24fc88c7d5ae', 'DFAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE());

/* SQL text to add special date field __mj_CreatedAt to entity indiana_tax.AppealAnalysisCompDecision */
ALTER TABLE [indiana_tax].[AppealAnalysisCompDecision] ADD [__mj_CreatedAt] DATETIMEOFFSET NULL;
GO

/* SQL text to add special date field __mj_CreatedAt to entity indiana_tax.AppealAnalysisCompDecision */
UPDATE [indiana_tax].[AppealAnalysisCompDecision] SET [__mj_CreatedAt] = GETUTCDATE() WHERE [__mj_CreatedAt] IS NULL;
GO

/* SQL text to add special date field __mj_CreatedAt to entity indiana_tax.AppealAnalysisCompDecision */
ALTER TABLE [indiana_tax].[AppealAnalysisCompDecision] ALTER COLUMN [__mj_CreatedAt] DATETIMEOFFSET NOT NULL;
GO

/* SQL text to add special date field __mj_CreatedAt to entity indiana_tax.AppealAnalysisCompDecision */
ALTER TABLE [indiana_tax].[AppealAnalysisCompDecision] ADD CONSTRAINT [DF_indiana_tax_AppealAnalysisCompDecision___mj_CreatedAt] DEFAULT GETUTCDATE() FOR [__mj_CreatedAt];
GO

/* SQL text to add special date field __mj_UpdatedAt to entity indiana_tax.AppealAnalysisCompDecision */
ALTER TABLE [indiana_tax].[AppealAnalysisCompDecision] ADD [__mj_UpdatedAt] DATETIMEOFFSET NULL;
GO

/* SQL text to add special date field __mj_UpdatedAt to entity indiana_tax.AppealAnalysisCompDecision */
UPDATE [indiana_tax].[AppealAnalysisCompDecision] SET [__mj_UpdatedAt] = GETUTCDATE() WHERE [__mj_UpdatedAt] IS NULL;
GO

/* SQL text to add special date field __mj_UpdatedAt to entity indiana_tax.AppealAnalysisCompDecision */
ALTER TABLE [indiana_tax].[AppealAnalysisCompDecision] ALTER COLUMN [__mj_UpdatedAt] DATETIMEOFFSET NOT NULL;
GO

/* SQL text to add special date field __mj_UpdatedAt to entity indiana_tax.AppealAnalysisCompDecision */
ALTER TABLE [indiana_tax].[AppealAnalysisCompDecision] ADD CONSTRAINT [DF_indiana_tax_AppealAnalysisCompDecision___mj_UpdatedAt] DEFAULT GETUTCDATE() FOR [__mj_UpdatedAt];
GO

/* SQL text to insert 11 new entity field(s) -- 4 excluded (Legal Authority Chunks, Legal Authority Sections, IBTR Decision Citations; unrelated, see header note above) */

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = 'fd321b63-4be1-4117-8bd5-71f692481505' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'ID')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'fd321b63-4be1-4117-8bd5-71f692481505',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100001,
            'ID',
            'ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            'newsequentialid()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            1,
            0,
            0,
            1,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = 'cc8980af-52c5-4b2d-8821-6abf7e6d832e' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'AppealAnalysisID')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'cc8980af-52c5-4b2d-8821-6abf7e6d832e',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100002,
            'AppealAnalysisID',
            'Appeal Analysis ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            '517C9950-0669-4474-93A1-9EF12F348879',
            'ID',
            0,
            0,
            1,
            0,
            0,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = '54e21301-876d-4051-800a-2fb83759f57f' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'SaleTransactionID')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '54e21301-876d-4051-800a-2fb83759f57f',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100003,
            'SaleTransactionID',
            'Sale Transaction ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            'A4BC54C2-AF4C-44B4-B7F2-39E480BA5485',
            'ID',
            0,
            0,
            1,
            0,
            0,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = 'b92e7b56-d877-4bb6-b965-9381e573ca17' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'IsIncluded')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'b92e7b56-d877-4bb6-b965-9381e573ca17',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100004,
            'IsIncluded',
            'Is Included',
            'True = included in the sales indication; false = available in the candidate pool but excluded by the analyst. No row for a given comp means "follow the batch''s own IsSelected default".',
            'bit',
            1,
            1,
            0,
            0,
            '(1)',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = '56683142-c331-4f8c-b696-cf3062392a50' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'SortOrder')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '56683142-c331-4f8c-b696-cf3062392a50',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100005,
            'SortOrder',
            'Sort Order',
            'Manual position among included comps. NULL means "follow the batch''s own SimilarityRank".',
            'int',
            4,
            10,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = '99e598b3-7756-4150-9d4d-bbbf7556d9c7' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = '__mj_CreatedAt')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '99e598b3-7756-4150-9d4d-bbbf7556d9c7',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100006,
            '__mj_CreatedAt',
            'Created At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = '4c1a75d0-2aaa-4c2f-ac2c-c16e6c21d78e' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = '__mj_UpdatedAt')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '4c1a75d0-2aaa-4c2f-ac2c-c16e6c21d78e',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100007,
            '__mj_UpdatedAt',
            'Updated At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* Create Entity Relationship: Sale Transactions -> Appeal Analysis Comp Decisions (One To Many via SaleTransactionID) */
   IF NOT EXISTS (
      SELECT 1 FROM [__mj].[EntityRelationship] WHERE [ID] = '7b06a1c8-ca1b-4ff5-884f-16da80abfdff'
   )
   BEGIN
      INSERT INTO [__mj].[EntityRelationship] ([ID], [EntityID], [RelatedEntityID], [RelatedEntityJoinField], [Type], [BundleInAPI], [DisplayInForm], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt])
                    VALUES ('7b06a1c8-ca1b-4ff5-884f-16da80abfdff', 'A4BC54C2-AF4C-44B4-B7F2-39E480BA5485', '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', 'SaleTransactionID', 'One To Many', 1, 1, 2, GETUTCDATE(), GETUTCDATE())
   END;


/* Create Entity Relationship: Appeal Analysis -> Appeal Analysis Comp Decisions (One To Many via AppealAnalysisID) */
   IF NOT EXISTS (
      SELECT 1 FROM [__mj].[EntityRelationship] WHERE [ID] = '4f80a927-93bc-472a-bbdf-682318ae9be8'
   )
   BEGIN
      INSERT INTO [__mj].[EntityRelationship] ([ID], [EntityID], [RelatedEntityID], [RelatedEntityJoinField], [Type], [BundleInAPI], [DisplayInForm], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt])
                    VALUES ('4f80a927-93bc-472a-bbdf-682318ae9be8', '517C9950-0669-4474-93A1-9EF12F348879', '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', 'AppealAnalysisID', 'One To Many', 1, 1, 3, GETUTCDATE(), GETUTCDATE())
   END;
-- [excluded: EntityField sequence fix for the pre-existing "Store Analysis" entity -- unrelated, see header note above]

/* Index for Foreign Keys for AppealAnalysisCompDecision */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Analysis Comp Decisions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key AppealAnalysisID in table AppealAnalysisCompDecision
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AppealAnalysisCompDecision_AppealAnalysisID' 
    AND object_id = OBJECT_ID('[indiana_tax].[AppealAnalysisCompDecision]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AppealAnalysisCompDecision_AppealAnalysisID ON [indiana_tax].[AppealAnalysisCompDecision] ([AppealAnalysisID]);

-- Index for foreign key SaleTransactionID in table AppealAnalysisCompDecision
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_AppealAnalysisCompDecision_SaleTransactionID' 
    AND object_id = OBJECT_ID('[indiana_tax].[AppealAnalysisCompDecision]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_AppealAnalysisCompDecision_SaleTransactionID ON [indiana_tax].[AppealAnalysisCompDecision] ([SaleTransactionID]);

/* SQL text to update entity field related entity name field map for entity field ID CC8980AF-52C5-4B2D-8821-6ABF7E6D832E */
EXEC [__mj].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='CC8980AF-52C5-4B2D-8821-6ABF7E6D832E', @RelatedEntityNameFieldMap='AppealAnalysis';

/* SQL text to update entity field related entity name field map for entity field ID 54E21301-876D-4051-800A-2FB83759F57F */
EXEC [__mj].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='54E21301-876D-4051-800A-2FB83759F57F', @RelatedEntityNameFieldMap='SaleTransaction';

/* Base View SQL for Appeal Analysis Comp Decisions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Analysis Comp Decisions
-- Item: vwAppealAnalysisCompDecisions
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Appeal Analysis Comp Decisions
-----               SCHEMA:      indiana_tax
-----               BASE TABLE:  AppealAnalysisCompDecision
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[vwAppealAnalysisCompDecisions]', 'V') IS NOT NULL
    DROP VIEW [indiana_tax].[vwAppealAnalysisCompDecisions];
GO

CREATE VIEW [indiana_tax].[vwAppealAnalysisCompDecisions]
AS
SELECT
    a.*,
    indianataxAppealAnalysis_AppealAnalysisID.[Name] AS [AppealAnalysis],
    indianataxSaleTransaction_SaleTransactionID.[SitusAddress] AS [SaleTransaction]
FROM
    [indiana_tax].[AppealAnalysisCompDecision] AS a
INNER JOIN
    [indiana_tax].[AppealAnalysis] AS indianataxAppealAnalysis_AppealAnalysisID
  ON
    [a].[AppealAnalysisID] = indianataxAppealAnalysis_AppealAnalysisID.[ID]
INNER JOIN
    [indiana_tax].[SaleTransaction] AS indianataxSaleTransaction_SaleTransactionID
  ON
    [a].[SaleTransactionID] = indianataxSaleTransaction_SaleTransactionID.[ID]
GO
GRANT SELECT ON [indiana_tax].[vwAppealAnalysisCompDecisions] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for Appeal Analysis Comp Decisions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Analysis Comp Decisions
-- Item: Permissions for vwAppealAnalysisCompDecisions
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [indiana_tax].[vwAppealAnalysisCompDecisions] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for Appeal Analysis Comp Decisions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Analysis Comp Decisions
-- Item: spCreateAppealAnalysisCompDecision
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR AppealAnalysisCompDecision
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spCreateAppealAnalysisCompDecision]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spCreateAppealAnalysisCompDecision];
GO

CREATE PROCEDURE [indiana_tax].[spCreateAppealAnalysisCompDecision]
    @ID uniqueidentifier = NULL,
    @AppealAnalysisID uniqueidentifier,
    @SaleTransactionID uniqueidentifier,
    @IsIncluded bit = NULL,
    @SortOrder_Clear bit = 0,
    @SortOrder int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [indiana_tax].[AppealAnalysisCompDecision]
            (
                [ID],
                [AppealAnalysisID],
                [SaleTransactionID],
                [IsIncluded],
                [SortOrder]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @AppealAnalysisID,
                @SaleTransactionID,
                ISNULL(@IsIncluded, 1),
                CASE WHEN @SortOrder_Clear = 1 THEN NULL ELSE ISNULL(@SortOrder, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [indiana_tax].[AppealAnalysisCompDecision]
            (
                [AppealAnalysisID],
                [SaleTransactionID],
                [IsIncluded],
                [SortOrder]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @AppealAnalysisID,
                @SaleTransactionID,
                ISNULL(@IsIncluded, 1),
                CASE WHEN @SortOrder_Clear = 1 THEN NULL ELSE ISNULL(@SortOrder, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [indiana_tax].[vwAppealAnalysisCompDecisions] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [indiana_tax].[spCreateAppealAnalysisCompDecision] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for Appeal Analysis Comp Decisions */

GRANT EXECUTE ON [indiana_tax].[spCreateAppealAnalysisCompDecision] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for Appeal Analysis Comp Decisions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Analysis Comp Decisions
-- Item: spUpdateAppealAnalysisCompDecision
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR AppealAnalysisCompDecision
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spUpdateAppealAnalysisCompDecision]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spUpdateAppealAnalysisCompDecision];
GO

CREATE PROCEDURE [indiana_tax].[spUpdateAppealAnalysisCompDecision]
    @ID uniqueidentifier,
    @AppealAnalysisID uniqueidentifier = NULL,
    @SaleTransactionID uniqueidentifier = NULL,
    @IsIncluded bit = NULL,
    @SortOrder_Clear bit = 0,
    @SortOrder int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[AppealAnalysisCompDecision]
    SET
        [AppealAnalysisID] = ISNULL(@AppealAnalysisID, [AppealAnalysisID]),
        [SaleTransactionID] = ISNULL(@SaleTransactionID, [SaleTransactionID]),
        [IsIncluded] = ISNULL(@IsIncluded, [IsIncluded]),
        [SortOrder] = CASE WHEN @SortOrder_Clear = 1 THEN NULL ELSE ISNULL(@SortOrder, [SortOrder]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [indiana_tax].[vwAppealAnalysisCompDecisions] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [indiana_tax].[vwAppealAnalysisCompDecisions]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [indiana_tax].[spUpdateAppealAnalysisCompDecision] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the AppealAnalysisCompDecision table
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[trgUpdateAppealAnalysisCompDecision]', 'TR') IS NOT NULL
    DROP TRIGGER [indiana_tax].[trgUpdateAppealAnalysisCompDecision];
GO
CREATE TRIGGER [indiana_tax].trgUpdateAppealAnalysisCompDecision
ON [indiana_tax].[AppealAnalysisCompDecision]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [indiana_tax].[AppealAnalysisCompDecision]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [indiana_tax].[AppealAnalysisCompDecision] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for Appeal Analysis Comp Decisions */

GRANT EXECUTE ON [indiana_tax].[spUpdateAppealAnalysisCompDecision] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for Appeal Analysis Comp Decisions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Appeal Analysis Comp Decisions
-- Item: spDeleteAppealAnalysisCompDecision
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR AppealAnalysisCompDecision
------------------------------------------------------------
IF OBJECT_ID('[indiana_tax].[spDeleteAppealAnalysisCompDecision]', 'P') IS NOT NULL
    DROP PROCEDURE [indiana_tax].[spDeleteAppealAnalysisCompDecision];
GO

CREATE PROCEDURE [indiana_tax].[spDeleteAppealAnalysisCompDecision]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [indiana_tax].[AppealAnalysisCompDecision]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [indiana_tax].[spDeleteAppealAnalysisCompDecision] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for Appeal Analysis Comp Decisions */

GRANT EXECUTE ON [indiana_tax].[spDeleteAppealAnalysisCompDecision] TO [cdp_Developer], [cdp_Integration];
-- [excluded: Index for Foreign Keys, base views, spCreate/spUpdate/spDelete procedures, and full-text search objects for IBTR Decision Citations, Legal Authority Chunks, and Legal Authority Sections -- unrelated, see header note above]

/* SQL text to insert 2 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = '2e5098a8-a3a7-4bcb-a461-49785484f019' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'AppealAnalysis')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '2e5098a8-a3a7-4bcb-a461-49785484f019',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100015,
            'AppealAnalysis',
            'Appeal Analysis',
            NULL,
            'nvarchar',
            400,
            0,
            0,
            0,
            NULL,
            0,
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [__mj].[EntityField] WHERE ID = '0da93f11-2544-433d-9d1b-5a8885d4ceb7' OR (EntityID = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE' AND Name = 'SaleTransaction')) BEGIN
         INSERT INTO [__mj].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '0da93f11-2544-433d-9d1b-5a8885d4ceb7',
            '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', -- Entity: Appeal Analysis Comp Decisions
            100016,
            'SaleTransaction',
            'Sale Transaction',
            NULL,
            'nvarchar',
            400,
            0,
            0,
            1,
            NULL,
            0,
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;
-- [excluded: field-property update (DefaultInView) for one unrelated field (Legal Authority Sections.LegalAuthority) -- unrelated, see header note above]

/* Set field properties for entity */

               UPDATE [__mj].[EntityField]
               SET DefaultInView = 1
               WHERE ID = 'B92E7B56-D877-4BB6-B965-9381E573CA17'
               AND AutoUpdateDefaultInView = 1;

               UPDATE [__mj].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '56683142-C331-4F8C-B696-CF3062392A50'
               AND AutoUpdateDefaultInView = 1;

               UPDATE [__mj].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '2E5098A8-A3A7-4BCB-A461-49785484F019'
               AND AutoUpdateDefaultInView = 1;

               UPDATE [__mj].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '0DA93F11-2544-433D-9D1B-5A8885D4CEB7'
               AND AutoUpdateDefaultInView = 1;

               UPDATE [__mj].[EntityField]
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '2E5098A8-A3A7-4BCB-A461-49785484F019'
               AND AutoUpdateIncludeInUserSearchAPI = 1;

               UPDATE [__mj].[EntityField]
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '0DA93F11-2544-433D-9D1B-5A8885D4CEB7'
               AND AutoUpdateIncludeInUserSearchAPI = 1;

               UPDATE [__mj].[EntityField]
               SET UserSearchPredicateAPI = 'BeginsWith'
               WHERE ID = '2E5098A8-A3A7-4BCB-A461-49785484F019'
               AND AutoUpdateUserSearchPredicate = 1;

               UPDATE [__mj].[EntityField]
               SET UserSearchPredicateAPI = 'BeginsWith'
               WHERE ID = '0DA93F11-2544-433D-9D1B-5A8885D4CEB7'
               AND AutoUpdateUserSearchPredicate = 1;
-- [excluded: field-property update (UserSearchPredicateAPI) for two unrelated fields (Legal Authority Chunks / Legal Authority Sections) -- unrelated, see header note above]

/* Set categories for 9 fields */

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.ID 
UPDATE [__mj].[EntityField]
SET 
   Category = 'System Metadata',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'FD321B63-4BE1-4117-8BD5-71F692481505' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.AppealAnalysisID 
UPDATE [__mj].[EntityField]
SET 
   Category = 'Analysis Reference',
   GeneratedFormSection = 'Category',
   DisplayName = 'Appeal Analysis',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'CC8980AF-52C5-4B2D-8821-6ABF7E6D832E' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.SaleTransactionID 
UPDATE [__mj].[EntityField]
SET 
   Category = 'Analysis Reference',
   GeneratedFormSection = 'Category',
   DisplayName = 'Sale Transaction',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '54E21301-876D-4051-800A-2FB83759F57F' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.IsIncluded 
UPDATE [__mj].[EntityField]
SET 
   Category = 'Decision Settings',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B92E7B56-D877-4BB6-B965-9381E573CA17' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.SortOrder 
UPDATE [__mj].[EntityField]
SET 
   Category = 'Decision Settings',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '56683142-C331-4F8C-B696-CF3062392A50' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.__mj_CreatedAt 
UPDATE [__mj].[EntityField]
SET 
   Category = 'System Metadata',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '99E598B3-7756-4150-9D4D-BBBF7556D9C7' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.__mj_UpdatedAt 
UPDATE [__mj].[EntityField]
SET 
   Category = 'System Metadata',
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '4C1A75D0-2AAA-4C2F-AC2C-C16E6C21D78E' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.AppealAnalysis 
UPDATE [__mj].[EntityField]
SET 
   Category = 'Analysis Reference',
   GeneratedFormSection = 'Category',
   DisplayName = 'Appeal Analysis Details',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '2E5098A8-A3A7-4BCB-A461-49785484F019' AND AutoUpdateCategory = 1;

-- UPDATE Entity Field Category Info Appeal Analysis Comp Decisions.SaleTransaction 
UPDATE [__mj].[EntityField]
SET 
   Category = 'Analysis Reference',
   GeneratedFormSection = 'Category',
   DisplayName = 'Sale Transaction Details',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0DA93F11-2544-433D-9D1B-5A8885D4CEB7' AND AutoUpdateCategory = 1;

/* Set entity icon to fa fa-check-circle */

               UPDATE [__mj].[Entity]
               SET [Icon] = 'fa fa-check-circle', [__mj_UpdatedAt] = GETUTCDATE()
               WHERE [ID] = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE';

/* Insert FieldCategoryInfo setting for entity */

               INSERT INTO [__mj].[EntitySetting] ([ID], [EntityID], [Name], [Value], [__mj_CreatedAt], [__mj_UpdatedAt])
               VALUES ('a067b1c2-cd09-405b-92c0-0d0d1cac3ba3', '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', 'FieldCategoryInfo', '{"Analysis Reference":{"icon":"fa fa-link","description":"References to the appeal analysis and comparable sale transaction being evaluated"},"Decision Settings":{"icon":"fa fa-sliders-h","description":"Analyst''s curation decisions including inclusion status and manual sort order"},"System Metadata":{"icon":"fa fa-cog","description":"System-managed audit and tracking fields"}}', GETUTCDATE(), GETUTCDATE());

/* Insert FieldCategoryIcons setting (legacy) */

               INSERT INTO [__mj].[EntitySetting] ([ID], [EntityID], [Name], [Value], [__mj_CreatedAt], [__mj_UpdatedAt])
               VALUES ('5fe8cd32-5261-4d84-8824-3a97d28b34e3', '2E095C07-DB60-4924-B3FA-24FC88C7D5AE', 'FieldCategoryIcons', '{"Analysis Reference":"fa fa-link","Decision Settings":"fa fa-sliders-h","System Metadata":"fa fa-cog"}', GETUTCDATE(), GETUTCDATE());

/* Set DefaultForNewUser=false for NEW entity (category: supporting, confidence: high) */

         UPDATE [__mj].[ApplicationEntity]
         SET [DefaultForNewUser] = 0, [__mj_UpdatedAt] = GETUTCDATE()
         WHERE [EntityID] = '2E095C07-DB60-4924-B3FA-24FC88C7D5AE';
