/* ============================================================================
   Indiana Property Tax Expert — Assessment.PTABOA*AV: what the columns hold
   for county-card sources
   v5.58.x (companion to V202609121958 Indiana_Tax_Card_History)

   The three PTABOA columns were described as "value after a PTABOA appeal
   determination". For Marion's sources that is what they hold. For a
   county-card source (Assessment.Source = 'LakePRC'; scripts/lib/
   county-card-sources.js) the loader fills them from the LATER certified
   column of the same year on the parcel's cards, whatever the county's
   reason for the change: of Lake's 1,517 revised parcel-years, 584 cite an
   appeal form (Rev. 134, Reval/134, Det/115), 1,035 a Form 113 notice of
   assessment change, 446 an annual re-trend, 91 a general reassessment and
   47 a split, reclassification, omission or correction. The reason is on
   CardValuationColumn.ReasonForChange / ReasonKind. Found by Plan C's final
   review (2026-09-13); the columns' descriptions now say so. No data change.
   ============================================================================ */

EXEC sp_updateextendedproperty @name = N'MS_Description',
    @value = N'Land value as revised after the original determination. For Marion sources: the value after a PTABOA appeal determination, NULL until an appeal on this parcel/year is decided. For a county-card source (Assessment.Source in scripts/lib/county-card-sources.js, e.g. LakePRC): the later certified column of the same year on the parcel''s cards, whatever the county''s reason -- an appeal form (Rev. 134, Det/115), a Form 113 notice, a re-trend, a split or a correction; the reason is CardValuationColumn.ReasonForChange / ReasonKind, and only ReasonKind = ''appeal'' is an appeal outcome. NULL when no later column differs.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'Assessment', @level2type = N'COLUMN', @level2name = N'PTABOALandAV';
EXEC sp_updateextendedproperty @name = N'MS_Description',
    @value = N'Improvement value as revised after the original determination. For Marion sources: the value after a PTABOA appeal determination, NULL until an appeal on this parcel/year is decided. For a county-card source (Assessment.Source in scripts/lib/county-card-sources.js, e.g. LakePRC): the later certified column of the same year on the parcel''s cards, whatever the county''s reason -- an appeal form (Rev. 134, Det/115), a Form 113 notice, a re-trend, a split or a correction; the reason is CardValuationColumn.ReasonForChange / ReasonKind, and only ReasonKind = ''appeal'' is an appeal outcome. NULL when no later column differs.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'Assessment', @level2type = N'COLUMN', @level2name = N'PTABOAImprovementAV';
EXEC sp_updateextendedproperty @name = N'MS_Description',
    @value = N'Total value as revised after the original determination. For Marion sources: the value after a PTABOA appeal determination, NULL until an appeal on this parcel/year is decided. For a county-card source (Assessment.Source in scripts/lib/county-card-sources.js, e.g. LakePRC): the later certified column of the same year on the parcel''s cards, whatever the county''s reason -- an appeal form (Rev. 134, Det/115), a Form 113 notice, a re-trend, a split or a correction; the reason is CardValuationColumn.ReasonForChange / ReasonKind, and only ReasonKind = ''appeal'' is an appeal outcome. NULL when no later column differs.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'Assessment', @level2type = N'COLUMN', @level2name = N'PTABOATotalAV';
GO


















































/* ============================================================================
   EVERYTHING BELOW WAS GENERATED BY THE MEMBERJUNCTION CODEGEN TOOL.
   CodeGen produced no statements for this migration (it only updates three
   column descriptions, which CodeGen reads into EntityField.Description).
   Its run file carried one unrelated regeneration -- an EntityField sequence
   update for Big_Box_Retail's "Store Analysis" virtual entity, a pre-existing
   CodeGen error on that entity -- which is excluded here as unrelated.
   ============================================================================ */
