/* ============================================================================
   Indiana Property Tax Expert — Form Catalog.
   v5.53.x

   The user wants a tool where a taxpayer attaches a DLGF form (e.g. Form
   113/PP) and gets back how to complete it, what other forms may also be
   needed, and -- critically -- the real deadline and what triggers it, with
   verification strong enough to trust for something legally consequential
   (a missed deadline can forfeit an appeal).

   Investigated live before writing this migration: fetched and fully read
   three real forms directly from forms.in.gov -- Form 113/PP (State Form
   21521), Form 130 (State Form 53958, which prints its own full appeal
   escalation flowchart), and Form 11 (State Form 21366). Then checked the
   existing schema before designing anything new (this project's own
   standing rule) and found indiana_tax.AppealStage / AppealStageStatute
   ALREADY correctly model the entire post-Form-130 escalation chain (7
   stages: File Form 130 -> Preliminary Meeting -> PTABOA Determination ->
   Appeal to IBTR (Form 131) -> IBTR Hearing -> Tax Court -> Supreme Court),
   each cited to a real SourceDocument and StatuteSection row. Cross-checked
   Stage 1's stored DeadlineDescription against the real Form 130 PDF just
   read -- it matches exactly, including the Form 11 (before/after May 1)
   split and the personal-property 45-day rule. Nothing needed rebuilding
   there.

   What was genuinely missing: nothing modeled the FORMS THEMSELVES as
   structured data -- AppealStage.FormRequired is a free-text label ("Form
   130", "Form 134", "Form 131") with no state form number, no "who files
   it"/"who receives it," no property-type scope, and no row at all for the
   NOTICE forms (11, 113/PP) that precede and trigger the appeal chain
   rather than being a stage within it. This table fills exactly that gap --
   it does not duplicate AppealStage's deadline/citation data, it links to
   it.

   Accuracy design: FormCatalog rows are populated by a human (via Claude,
   reading the real form PDF directly) once per form, hardcoded as literal
   data in populate-form-catalog.js -- not generated by an LLM at query
   time. The tool's eventual agent-facing use of this table (a later pass)
   should only ever look up and cite from these hand-verified rows, never
   free-generate a deadline or citation.
   ============================================================================ */

CREATE TABLE indiana_tax.FormCatalog (
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    StateFormNumber NVARCHAR(20) NOT NULL,
    FormLabel NVARCHAR(30) NOT NULL,
    FullTitle NVARCHAR(300) NOT NULL,
    RevisionCode NVARCHAR(30) NULL,
    Purpose NVARCHAR(MAX) NOT NULL,
    FiledBy NVARCHAR(100) NOT NULL,
    FiledWith NVARCHAR(200) NULL,
    PropertyTypeScope NVARCHAR(20) NOT NULL
        CONSTRAINT CK_FormCatalog_PropertyTypeScope CHECK (PropertyTypeScope IN ('Real', 'Personal', 'Both', 'PublicUtility')),
    CorrespondingAppealStageID UNIQUEIDENTIFIER NULL,
    TriggersAppealStageID UNIQUEIDENTIFIER NULL,
    SourceDocumentID UNIQUEIDENTIFIER NOT NULL,
    SourceURL NVARCHAR(500) NOT NULL,
    LastVerifiedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT PK_FormCatalog PRIMARY KEY (ID),
    CONSTRAINT UQ_FormCatalog_StateFormNumber UNIQUE (StateFormNumber),
    CONSTRAINT FK_FormCatalog_CorrespondingAppealStage FOREIGN KEY (CorrespondingAppealStageID) REFERENCES indiana_tax.AppealStage(ID),
    CONSTRAINT FK_FormCatalog_TriggersAppealStage FOREIGN KEY (TriggersAppealStageID) REFERENCES indiana_tax.AppealStage(ID),
    CONSTRAINT FK_FormCatalog_SourceDocument FOREIGN KEY (SourceDocumentID) REFERENCES indiana_tax.SourceDocument(ID)
);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The number printed on every DLGF form itself (e.g. "21521", "53958", "21366") -- the reliable, near-deterministic way to identify which form a taxpayer uploaded, before any interpretive/LLM matching is needed.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'StateFormNumber';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The colloquial form name (e.g. "Form 113/PP", "Form 130", "Form 11") -- deliberately matches AppealStage.FormRequired''s own free-text convention exactly, so the two can be joined/compared as plain strings.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'FormLabel';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The form''s full official title as printed (e.g. "Notice of Assessment / Change by an Assessing Official").',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'FullTitle';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The revision code printed on the form (e.g. "R12 / 10-19") -- forms get revised periodically; this records which revision was actually verified against, so a later revision can be detected as needing re-verification.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'RevisionCode';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Plain-language description of what this form is for and when it''s used.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'Purpose';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Who completes/files this form (e.g. "Assessing Official", "Taxpayer").',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'FiledBy';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Who receives this form (e.g. "Township Assessor or County Assessor"). Null for a form that is only issued outward (a notice), not filed with anyone.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'FiledWith';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Which kind of property this form applies to -- Real, Personal, Both, or PublicUtility.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'PropertyTypeScope';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'For a form that IS a step in the appeal process (Form 130, 131, 134): the indiana_tax.AppealStage row it corresponds to -- that row already carries the authoritative deadline/citation, not duplicated here. Null for a form that is not itself an appeal-process step.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'CorrespondingAppealStageID';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'For a NOTICE form (e.g. Form 11, Form 113/PP) whose issuance is what starts the clock on a downstream appeal-process step: the indiana_tax.AppealStage row it triggers. Null for a form that is not a triggering notice. A form should generally have exactly one of CorrespondingAppealStageID or TriggersAppealStageID set, not both -- not enforced by a CHECK since the distinction isn''t safety-critical, just documented here.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'TriggersAppealStageID';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The SourceDocument row for this form''s own actual PDF (DocumentType = ''Form'', same convention already used for AppealStage.SourceDocumentID''s Form 130 row) -- every catalog row traces back to a real, hashed, retained document, not an assertion.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'SourceDocumentID';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The forms.in.gov download URL this form was fetched from.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'SourceURL';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'When this row was last verified against the actual form text -- distinct from __mj_UpdatedAt, which would also change on a purely mechanical edit.',
    @level0type = N'SCHEMA', @level0name = N'indiana_tax', @level1type = N'TABLE', @level1name = N'FormCatalog', @level2type = N'COLUMN', @level2name = N'LastVerifiedAt';
GO
