/* ============================================================================
   Indiana Property Tax Expert — St. Joseph County record cards as a source
   v5.58.x (companion to V202609121958 Indiana_Tax_Card_History)

   The second county loaded from its own record cards (intake runbook,
   Indiana_Tax_Expert/docs/proposals/multi-county-ci-intake.md §7): every
   St. Joseph C&I parcel-year loads as Assessment.Source = 'StJosephPRC',
   the county-card pattern set by 'LakePRC'. CK_Assessment_ComponentSum --
   land + improvement = total, within $1, for the authoritative sources --
   is widened to it. No other change; no data change.
   ============================================================================ */

ALTER TABLE indiana_tax.Assessment DROP CONSTRAINT CK_Assessment_ComponentSum;
GO
ALTER TABLE indiana_tax.Assessment ADD CONSTRAINT CK_Assessment_ComponentSum CHECK (
    Source NOT IN ('MarionPRC', 'marion_foia_2026', 'LakePRC', 'StJosephPRC')
    OR OriginalLandAV IS NULL OR OriginalImprovementAV IS NULL OR OriginalTotalAV IS NULL
    OR ABS(OriginalLandAV + OriginalImprovementAV - OriginalTotalAV) <= 1);
GO


















































/* ============================================================================
   EVERYTHING BELOW WAS GENERATED BY THE MEMBERJUNCTION CODEGEN TOOL.
   CodeGen produced no statements for this migration: the CHECK is a
   multi-column expression, which yields no value list and changes no view
   or procedure. Its run file (CodeGen_Run_2026-09-13_18-15-18.sql) carried
   only the pre-existing "Store Analysis" EntityField sequence update,
   excluded as unrelated; that run file is deleted.
   ============================================================================ */
